# Generated by Django 4.2.3 on 2024-09-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_managements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='full_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessdetail',
            name='gstin_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessdetail',
            name='pan_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessdetail',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='business_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='business_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
