# Generated by Django 4.2.3 on 2026-01-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("org_managements", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businessdetail",
            options={
                "ordering": ("created",),
                "verbose_name": "Business",
                "verbose_name_plural": "Businesses",
            },
        ),
    ]
