# Generated by Django 4.2.3 on 2024-10-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_managements', '0002_businessdetail_full_address_businessdetail_gstin_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='domain_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
