# Generated by Django 4.2.3 on 2024-10-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_managements', '0003_businessdetail_domain_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='full_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
