# Generated by Django 4.2.3 on 2024-11-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_managements', '0004_alter_businessdetail_full_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='active',
            field=models.BooleanField(default=False, help_text='Whether the business is active.'),
        ),
        migrations.AddField(
            model_name='businessdetail',
            name='hsn_sac_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='business_logo',
            field=models.FileField(blank=True, null=True, upload_to='business/logo/'),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='business_name',
            field=models.CharField(max_length=150),
        ),
    ]
