# Generated by Django 4.2.3 on 2024-12-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_managements', '0005_businessdetail_active_businessdetail_hsn_sac_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
