# Generated by Django 4.2.3 on 2024-12-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_discount_type_alter_coupon_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_type',
        ),
        migrations.AddField(
            model_name='coupon',
            name='booking_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='booking_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_booking_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_stay_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='stay_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='stay_start_date',
            field=models.DateField(null=True),
        ),
    ]
