# Generated by Django 4.2.3 on 2024-12-12 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0038_propertybankdetails'),
        ('coupons', '0004_remove_coupon_valid_from_remove_coupon_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_coupon', to='hotels.property'),
        ),
    ]
