# Generated by Django 4.2.3 on 2026-03-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0004_user_coupon_claim"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="couponredemption",
            new_name="coupons_cou_coupon__45633e_idx",
            old_name="coupons_cou_coupon__idx",
        ),
        migrations.RenameIndex(
            model_name="couponredemption",
            new_name="coupons_cou_booking_b98027_idx",
            old_name="coupons_cou_booking_idx",
        ),
        migrations.RenameIndex(
            model_name="usercouponclaim",
            new_name="coupons_use_coupon__a0beca_idx",
            old_name="coupons_use_coupon__fdb29e_idx",
        ),
        migrations.RenameIndex(
            model_name="usercouponclaim",
            new_name="coupons_use_user_id_c280a4_idx",
            old_name="coupons_use_user_id_6f39d2_idx",
        ),
        migrations.AlterField(
            model_name="coupon",
            name="use_coupon_value_override",
            field=models.BooleanField(
                default=False,
                help_text="If true, when campaign slabs are configured, coupon.discount is used as a maximum discount cap (slabs still apply).",
            ),
        ),
    ]
