# Generated by Django 4.2.3 on 2025-11-13 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("org_resources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, default="", max_length=50)),
                (
                    "amount",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("Credit", "Credit"), ("Debit", "Debit")],
                        help_text="Credit / Debit",
                        max_length=10,
                    ),
                ),
                (
                    "transaction_for",
                    models.CharField(
                        choices=[
                            ("booking_confirmed", "booking_confirmed"),
                            ("booking_refund", "booking_refund"),
                            ("referral_booking", "referral_booking"),
                            ("booking_refund", "booking_refund"),
                            ("booking_cashback", "booking_cashback"),
                            ("signup_reward", "signup_reward"),
                            ("pro_member_bonus", "pro_member_bonus"),
                            ("pro_member_bonus_expiry", "pro_member_bonus_expiry"),
                            ("wallet_recharge", "wallet_recharge"),
                            ("others", "others"),
                        ],
                        default="others",
                        max_length=30,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="transaction id",
                        max_length=350,
                        null=True,
                    ),
                ),
                (
                    "transaction_details",
                    models.TextField(help_text="Transaction description"),
                ),
                ("other_details", models.JSONField(default=dict, null=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("PAYMENT GATEWAY", "PAYMENT GATEWAY"),
                            ("WALLET", "WALLET"),
                            ("NBFC", "NBFC"),
                            ("DIRECT", "DIRECT"),
                            ("BANK TRANSFER", "BANK TRANSFER"),
                        ],
                        default="WALLET",
                        max_length=50,
                    ),
                ),
                (
                    "payment_medium",
                    models.CharField(
                        choices=[
                            ("PHONE PAY", "PHONE PAY"),
                            ("PayU", "PayU"),
                            ("Idbook", "Idbook"),
                            ("Hotel", "Hotel"),
                            ("NEFT", "NEFT"),
                            ("RTGS", "RTGS"),
                            ("IMPS", "IMPS"),
                            ("UPI", "UPI"),
                            ("NET_BANKING", "Net Banking"),
                            ("Others", "Others"),
                        ],
                        default="Idbook",
                        max_length=50,
                    ),
                ),
                ("is_transaction_success", models.BooleanField(default=False)),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Expiry date for pro wallet credit amount",
                        null=True,
                    ),
                ),
                (
                    "used_amount",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Amount used from pro wallet",
                        max_digits=20,
                    ),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Remaining amount from pro wallet",
                        max_digits=20,
                    ),
                ),
                (
                    "is_expired",
                    models.BooleanField(
                        default=False,
                        help_text="Flag to indicate if a pro wallet credit has been expired and processed",
                    ),
                ),
                (
                    "media",
                    models.FileField(
                        blank=True, null=True, upload_to="wallet/transactions/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                            ("Others", "Others"),
                        ],
                        default="Completed",
                        max_length=100,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wallet_company_transaction",
                        to="org_resources.companydetail",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wallet_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=6, default=0, max_digits=20
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wallet_company",
                        to="org_resources.companydetail",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wallet_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Full address",
                        null=True,
                        verbose_name="customer_address",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        help_text="Select the gender of the customer.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Enter the date of birth of the customer.",
                        null=True,
                    ),
                ),
                (
                    "profile_picture",
                    models.FileField(
                        blank=True, null=True, upload_to="customer/profile/"
                    ),
                ),
                (
                    "id_proof_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADHAR CARD", "ADHAR CARD"),
                            ("VOTER ID CARD", "VOTER ID CARD"),
                            ("DRIVING LICENCE", "DRIVING LICENCE"),
                            ("Others", "Others"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "id_proof",
                    models.FileField(
                        blank=True, null=True, upload_to="customer/idproof/"
                    ),
                ),
                (
                    "pan_card",
                    models.FileField(
                        blank=True, null=True, upload_to="customer/idproof/"
                    ),
                ),
                (
                    "pan_card_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "aadhar_card",
                    models.FileField(
                        blank=True, null=True, upload_to="customer/idproof/"
                    ),
                ),
                (
                    "aadhar_card_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "loyalty_points",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total loyalty points earned by the customer.",
                    ),
                ),
                (
                    "membership_status",
                    models.BooleanField(
                        default=False,
                        help_text="Check if the customer has a membership.",
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the customer's emergency contact person.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number of the customer's emergency contact.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        blank=True,
                        choices=[("English", "English"), ("Hindi", "Hindi")],
                        help_text="Preferred language of communication for the customer.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "dietary_restrictions",
                    models.TextField(
                        blank=True,
                        help_text="Any dietary restrictions or preferences for the customer.",
                        null=True,
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(
                        blank=True,
                        help_text="Any special requests or notes from the customer.",
                        null=True,
                    ),
                ),
                (
                    "group_name",
                    models.CharField(
                        choices=[
                            ("ORG", "ORG"),
                            ("ADMIN", "ADMIN"),
                            ("DEFAULT", "DEFAULT"),
                        ],
                        default="DEFAULT",
                        help_text="Group for the customer.",
                        max_length=10,
                    ),
                ),
                ("employee_id", models.CharField(blank=True, max_length=20, null=True)),
                ("department", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "privileged",
                    models.BooleanField(
                        default=False, help_text="Whether the customer is privileged."
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False, help_text="Whether the customer is active."
                    ),
                ),
                ("state", models.CharField(blank=True, default="", max_length=50)),
                ("country", models.CharField(blank=True, default="", max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "added_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Confirmed / Added User",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="user profile in user table",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="customer_profile",
                    ),
                ),
            ],
        ),
    ]
