# Generated by Django 4.2.3 on 2023-08-17 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_resources', '0008_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text='Select the gender of the customer.', max_length=10)),
                ('date_of_birth', models.DateField(help_text='Enter the date of birth of the customer.')),
                ('loyalty_points', models.PositiveIntegerField(default=0, help_text='Total loyalty points earned by the customer.')),
                ('membership_status', models.BooleanField(default=False, help_text='Check if the customer has a membership.')),
                ('emergency_contact_name', models.CharField(blank=True, help_text="Name of the customer's emergency contact person.", max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text="Phone number of the customer's emergency contact.", max_length=20, null=True)),
                ('preferred_language', models.CharField(blank=True, help_text='Preferred language of communication for the customer.', max_length=20)),
                ('dietary_restrictions', models.TextField(blank=True, help_text='Any dietary restrictions or preferences for the customer.')),
                ('special_requests', models.TextField(blank=True, help_text='Any special requests or notes from the customer.')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org_resources.address', verbose_name='customer_address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='customer_profile')),
            ],
        ),
    ]
