# Generated by Django 4.2.3 on 2026-01-13 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("org_resources", "0004_agentmarkupconfig"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="agents",
            field=models.ManyToManyField(
                blank=True,
                help_text="Agents linked to this customer (can have multiple)",
                related_name="customers",
                to="org_resources.agentdetail",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="primary_agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary agent for this customer (most recent or manually set)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_customers",
                to="org_resources.agentdetail",
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent this wallet belongs to",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="wallet_agent",
                to="org_resources.agentdetail",
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent this transaction belongs to",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="wallet_agent_transaction",
                to="org_resources.agentdetail",
            ),
        ),
    ]
