# Generated by Django 4.2.3 on 2023-08-17 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='aadhar_card',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='aadhar_card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=False, help_text='Whether the customer is active.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='id_proof',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_proof_type',
            field=models.CharField(blank=True, choices=[('ADHAR CARD', 'ADHAR CARD'), ('VOTER ID CARD', 'VOTER ID CARD'), ('DRIVING LICENCE', 'DRIVING LICENCE'), ('Others', 'Others')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pan_card',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='pan_card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='privileged',
            field=models.BooleanField(default=False, help_text='Whether the customer is privileged.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text="Phone number of the customer's emergency contact.", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Hindi', 'Hindi')], help_text='Preferred language of communication for the customer.', max_length=20),
        ),
    ]
