# Generated by Django 4.2.3 on 2026-01-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customer",
            "0002_customer_agents_customer_primary_agent_wallet_agent_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="transaction_for",
            field=models.CharField(
                choices=[
                    ("booking_confirmed", "booking_confirmed"),
                    ("booking_refund", "booking_refund"),
                    ("referral_booking", "referral_booking"),
                    ("booking_cashback", "booking_cashback"),
                    ("signup_reward", "signup_reward"),
                    ("pro_member_bonus", "pro_member_bonus"),
                    ("pro_member_bonus_expiry", "pro_member_bonus_expiry"),
                    ("wallet_recharge", "wallet_recharge"),
                    ("others", "others"),
                ],
                default="others",
                max_length=30,
            ),
        ),
    ]
