# Generated by Django 4.2.3 on 2026-05-05 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_resources', '0007_alter_messagetemplate_template_type_default'),
        ('customer', '0005_wallet_exclusive_owner_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wallet_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wallet_company_transaction', to='org_resources.companydetail'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
