# Generated by Django 4.2.3 on 2024-10-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_added_user_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dietary_restrictions',
            field=models.TextField(blank=True, help_text='Any dietary restrictions or preferences for the customer.', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='customer/id/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Hindi', 'Hindi')], help_text='Preferred language of communication for the customer.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='special_requests',
            field=models.TextField(blank=True, help_text='Any special requests or notes from the customer.', null=True),
        ),
    ]
