# Generated by Django 4.2.3 on 2026-05-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_wallet_wallettransaction_blank_null_fks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='other_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
