# Generated by Django 4.2.3 on 2024-10-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_customer_aadhar_card_alter_customer_id_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, help_text='Full address', max_length=100, null=True, verbose_name='customer_address'),
        ),
    ]
