# Generated by Django 4.2.3 on 2024-10-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='department',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='group_name',
            field=models.CharField(choices=[('ORG', 'ORG'), ('ADMIN', 'ADMIN'), ('DEFAULT', 'DEFAULT')], default='DEFAULT', help_text='Group for the customer.', max_length=10),
        ),
    ]
