# Generated by Django 4.2.3 on 2024-10-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_customer_department_customer_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, help_text='Full address', null=True, verbose_name='customer_address'),
        ),
    ]
