# Generated by Django 4.2.3 on 2025-02-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_customer_country_customer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='is_transaction_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='payment_medium',
            field=models.CharField(choices=[('PHONE PAY', 'PHONE PAY'), ('Idbook', 'Idbook')], default='Idbook', max_length=50),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='payment_type',
            field=models.CharField(choices=[('PAYMENT GATEWAY', 'PAYMENT GATEWAY'), ('WALLET', 'WALLET'), ('NBFC', 'NBFC')], default='WALLET', max_length=50),
        ),
    ]
