# Generated by Django 4.2.3 on 2025-03-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_wallettransaction_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='other_details',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_for',
            field=models.CharField(choices=[('booking_confirmed', 'booking_confirmed'), ('booking_refund', 'booking_refund'), ('referral_booking', 'referral_booking'), ('booking_refund', 'booking_refund'), ('others', 'others')], default='others', max_length=30),
        ),
    ]
