# Generated by Django 4.2.3 on 2025-04-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_alter_wallettransaction_transaction_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='payment_medium',
            field=models.CharField(choices=[('PHONE PAY', 'PHONE PAY'), ('PayU', 'PayU'), ('Idbook', 'Idbook'), ('Hotel', 'Hotel')], default='Idbook', max_length=50),
        ),
    ]
