# Generated by Django 4.2.3 on 2025-05-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_alter_wallettransaction_transaction_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date for pro wallet credit amount', null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Remaining amount from pro wallet', max_digits=20),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='used_amount',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Amount used from pro wallet', max_digits=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_for',
            field=models.CharField(choices=[('booking_confirmed', 'booking_confirmed'), ('booking_refund', 'booking_refund'), ('referral_booking', 'referral_booking'), ('booking_refund', 'booking_refund'), ('booking_cashback', 'booking_cashback'), ('signup_reward', 'signup_reward'), ('pro_member_bonus', 'pro_member_bonus'), ('pro_member_bonus_expiry', 'pro_member_bonus_expiry'), ('others', 'others')], default='others', max_length=30),
        ),
    ]
