# Generated by Django 4.2.3 on 2025-05-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_alter_wallettransaction_transaction_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date for pro wallet credit amount', null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Remaining amount from pro wallet', max_digits=20),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='used_amount',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Amount used from pro wallet', max_digits=20),
        ),
    ]
