# Generated by Django 4.2.3 on 2025-05-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_wallettransaction_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='expiry_date',
            field=models.DateTimeField(blank=True, help_text='Expiry date for pro wallet credit amount', null=True),
        ),
    ]
