# Generated by Django 4.2.3 on 2025-05-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_alter_wallettransaction_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='is_expired',
            field=models.BooleanField(default=False, help_text='Flag to indicate if a pro wallet credit has been expired and processed'),
        ),
    ]
