# Generated by Django 4.2.3 on 2025-05-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_wallettransaction_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='wallet/transactions/'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Others', 'Others')], default='Completed', max_length=100),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_for',
            field=models.CharField(choices=[('booking_confirmed', 'booking_confirmed'), ('booking_refund', 'booking_refund'), ('referral_booking', 'referral_booking'), ('booking_refund', 'booking_refund'), ('booking_cashback', 'booking_cashback'), ('signup_reward', 'signup_reward'), ('pro_member_bonus', 'pro_member_bonus'), ('pro_member_bonus_expiry', 'pro_member_bonus_expiry'), ('wallet_recharge', 'wallet_recharge'), ('others', 'others')], default='others', max_length=30),
        ),
    ]
