# Generated by Django 4.2.3 on 2025-11-07 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0051_basicrulesconfig'),
        ('customer', '0030_alter_wallettransaction_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wallet_company', to='org_resources.companydetail'),
        ),
    ]
