# Generated by Django 4.2.3 on 2026-01-09 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="business_rep",
            field=models.ForeignKey(
                blank=True,
                help_text="Business representative (account manager) assigned to this property.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="property_business_rep",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
