# Generated by Django 4.2.3 on 2023-07-11 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('body', models.TextField(blank=True)),
                ('check_in_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('breakfast', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cleanliness', models.DecimalField(decimal_places=2, max_digits=3)),
                ('comfort', models.DecimalField(decimal_places=2, max_digits=3)),
                ('hotel_staff', models.DecimalField(decimal_places=2, max_digits=3)),
                ('facilities', models.DecimalField(decimal_places=2, max_digits=3)),
                ('over_all', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='hotels.hotel')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
