# Generated by Django 4.2.3 on 2023-07-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_gallery_image_type_alter_gallery_upload_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.CharField(default='INDIA', max_length=25),
        ),
    ]
