# Generated by Django 4.2.3 on 2023-08-11 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_hotel_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('-price_for_4_hours',), 'verbose_name': 'room', 'verbose_name_plural': 'rooms'},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='area',
            new_name='carpet_area',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
        migrations.AddField(
            model_name='hotel',
            name='custom_id',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='custom_id',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='price_for_12_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='room',
            name='price_for_24_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='room',
            name='price_for_4_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='room',
            name='price_for_8_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_type',
            field=models.CharField(choices=[('DELUXE', 'DELUXE'), ('CLASSIC', 'CLASSIC'), ('PREMIUM', 'PREMIUM'), ('HOTEL', 'HOTEL'), ('BATHROOM', 'BATHROOM'), ('SURROUNDING', 'SURROUNDING')], max_length=25),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='hotels.hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('DELUXE', 'DELUXE'), ('CLASSIC', 'CLASSIC'), ('PREMIUM', 'PREMIUM')], default='DELUXE', max_length=25),
        ),
    ]
