# Generated by Django 4.2.3 on 2023-08-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_room_options_rename_area_room_carpet_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='custom_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
