# Generated by Django 4.2.3 on 2023-08-12 04:13

import IDBOOKAPI.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0006_remove_bankdetail_google_pay_number_and_more'),
        ('hotels', '0006_alter_room_custom_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(choices=[('Hotel', 'Hotel'), ('Hotel & Restaurant', 'Hotel & Restaurant'), ('Hotel, Bar & Restaurant', 'Hotel, Bar & Restaurant'), ('Hotel & Bar', 'Hotel & Bar'), ('Hotel, Bar, Spa & Restaurant', 'Hotel, Bar, Spa & Restaurant')], default='', max_length=255)),
                ('custom_id', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('slug', models.SlugField(max_length=200)),
                ('checkin_time', models.TimeField(default=IDBOOKAPI.utils.get_default_time)),
                ('checkout_time', models.TimeField(default=IDBOOKAPI.utils.get_default_time)),
                ('full_address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Pondicherry', 'Pondicherry'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default='', max_length=30)),
                ('country', models.CharField(default='INDIA', max_length=25)),
                ('pin_code', models.PositiveIntegerField()),
                ('location', models.CharField(help_text='Google map URL', max_length=255)),
                ('area_name', models.CharField(help_text='Area Name', max_length=60)),
                ('city_name', models.CharField(help_text='City Name', max_length=35)),
                ('latitude', models.FloatField(default=0, help_text='Latitude')),
                ('longitude', models.FloatField(default=0, help_text='Longitude')),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amenity', models.ManyToManyField(related_name='property_amenities', to='org_resources.amenity')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ('-created',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='review',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.AddField(
            model_name='gallery',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_gallery', to='hotels.room'),
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.AddField(
            model_name='gallery',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_gallery', to='hotels.property'),
        ),
        migrations.AddField(
            model_name='review',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_review', to='hotels.property'),
        ),
        migrations.AddField(
            model_name='room',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_room', to='hotels.property'),
        ),
    ]
