# Generated by Django 4.2.3 on 2023-08-12 05:19

import IDBOOKAPI.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0006_remove_bankdetail_google_pay_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0007_property_remove_gallery_hotel_remove_review_hotel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='time_duration',
        ),
        migrations.AddField(
            model_name='property',
            name='featured_image',
            field=models.URLField(default='', help_text='URL of the featured image for the property.'),
        ),
        migrations.AddField(
            model_name='property',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Select a user as the property manager.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Rating of the property.', max_digits=3),
        ),
        migrations.AddField(
            model_name='property',
            name='total_rooms',
            field=models.PositiveIntegerField(default=1, help_text='Total number of rooms in the property.'),
        ),
        migrations.AddField(
            model_name='room',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether the room is active.'),
        ),
        migrations.AddField(
            model_name='room',
            name='bed_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of beds in the room.'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether the gallery image is active.'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the gallery image was created.'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_type',
            field=models.CharField(choices=[('DELUXE', 'DELUXE'), ('CLASSIC', 'CLASSIC'), ('PREMIUM', 'PREMIUM'), ('HOTEL', 'HOTEL'), ('BATHROOM', 'BATHROOM'), ('SURROUNDING', 'SURROUNDING')], help_text='Select the type of image in the gallery.', max_length=25),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='property',
            field=models.ForeignKey(blank=True, help_text='Select the property for which this gallery image belongs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_gallery', to='hotels.property'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Select the room for which this gallery image belongs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_gallery', to='hotels.room'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the gallery image was last updated.'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='upload_image',
            field=models.CharField(help_text='Enter the path or URL of the uploaded image.', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='active',
            field=models.BooleanField(default=False, help_text='Whether the property is active.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenity',
            field=models.ManyToManyField(help_text='Select amenities for this property.', related_name='property_amenities', to='org_resources.amenity'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area_name',
            field=models.CharField(help_text='Area name where the property is located.', max_length=60),
        ),
        migrations.AlterField(
            model_name='property',
            name='checkin_time',
            field=models.TimeField(default=IDBOOKAPI.utils.get_default_time, help_text='Check-in time for the property.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='checkout_time',
            field=models.TimeField(default=IDBOOKAPI.utils.get_default_time, help_text='Check-out time for the property.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city_name',
            field=models.CharField(help_text='City name where the property is located.', max_length=35),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(default='INDIA', help_text='Country of the property.', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the property was created.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='custom_id',
            field=models.CharField(blank=True, db_index=True, help_text='Custom ID for the property.', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(help_text='Description of the property.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.CharField(help_text='District of the property.', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='email',
            field=models.EmailField(help_text='Contact email for the property.', max_length=254),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured',
            field=models.BooleanField(default=False, help_text='Whether the property is featured.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='full_address',
            field=models.CharField(help_text='Full address of the property.', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.FloatField(default=0, help_text='Latitude of the property location.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(help_text='Google map URL for the property location.', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.FloatField(default=0, help_text='Longitude of the property location.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the property.', max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='phone_no',
            field=models.CharField(help_text='Contact phone number for the property.', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='pin_code',
            field=models.PositiveIntegerField(help_text='PIN code of the property.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='service_category',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Hotel & Restaurant', 'Hotel & Restaurant'), ('Hotel, Bar & Restaurant', 'Hotel, Bar & Restaurant'), ('Hotel & Bar', 'Hotel & Bar'), ('Hotel, Bar, Spa & Restaurant', 'Hotel, Bar, Spa & Restaurant')], default='', help_text='Select the service category for this property.', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(help_text='Slug for the property URL.', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Starting price for the property.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(choices=[('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Pondicherry', 'Pondicherry'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default='', help_text='State of the property.', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the property was last updated.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether the review is active.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(help_text='Body of the review text.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='breakfast',
            field=models.DecimalField(decimal_places=2, help_text='Rating for breakfast quality.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='check_in_rating',
            field=models.DecimalField(decimal_places=2, help_text='Rating for check-in experience.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='cleanliness',
            field=models.DecimalField(decimal_places=2, help_text='Rating for cleanliness.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='comfort',
            field=models.DecimalField(decimal_places=2, help_text='Rating for comfort.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the review was created.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(help_text='Email of the person submitting the review.', max_length=254),
        ),
        migrations.AlterField(
            model_name='review',
            name='facilities',
            field=models.DecimalField(decimal_places=2, help_text='Rating for facilities provided.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='hotel_staff',
            field=models.DecimalField(decimal_places=2, help_text='Rating for hotel staff service.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(help_text='Name of the person submitting the review.', max_length=80),
        ),
        migrations.AlterField(
            model_name='review',
            name='over_all',
            field=models.DecimalField(decimal_places=2, help_text='Overall rating for the property.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='property',
            field=models.ForeignKey(blank=True, help_text='Select the property for which this review is submitted.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_review', to='hotels.property'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the review was last updated.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(help_text='Select amenities available in this room.', related_name='rooms_amenities', to='org_resources.amenity'),
        ),
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.BooleanField(default=False, help_text='Whether the room is available for booking.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='carpet_area',
            field=models.PositiveSmallIntegerField(default=100, help_text='Carpet area of the room in square feet.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='child_capacity',
            field=models.PositiveSmallIntegerField(default=0, help_text='Maximum number of children the room can accommodate.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the room was created.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='custom_id',
            field=models.CharField(blank=True, db_index=True, help_text='Custom ID for the room.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, help_text='Discount percentage for the room (maximum 90%).'),
        ),
        migrations.AlterField(
            model_name='room',
            name='person_capacity',
            field=models.PositiveSmallIntegerField(default=1, help_text='Maximum number of adults the room can accommodate.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_for_12_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for a 12-hour stay in the room.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_for_24_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for a 24-hour stay in the room.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_for_4_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for a 4-hour stay in the room.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_for_8_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for an 8-hour stay in the room.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per night for the room.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='property',
            field=models.ForeignKey(blank=True, help_text='Select the property this room belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_room', to='hotels.property'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('DELUXE', 'DELUXE'), ('CLASSIC', 'CLASSIC'), ('PREMIUM', 'PREMIUM')], default='DELUXE', help_text='Select the type of room.', max_length=25),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the room was last updated.'),
        ),
    ]
