# Generated by Django 4.2.3 on 2023-08-17 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0008_address'),
        ('hotels', '0009_alter_property_country_alter_property_pin_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='country',
        ),
        migrations.RemoveField(
            model_name='property',
            name='district',
        ),
        migrations.RemoveField(
            model_name='property',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='property',
            name='state',
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='org_resources.address', verbose_name='property_address'),
        ),
    ]
