# Generated by Django 4.2.3 on 2024-01-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_property_build_year_property_chain_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area_name',
            field=models.CharField(blank=True, help_text='Area name where the property is located.', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='city_name',
            field=models.CharField(blank=True, help_text='City name where the property is located.', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, help_text='Google map URL for the property location.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug for the property URL.', max_length=200, null=True),
        ),
    ]
