# Generated by Django 4.2.3 on 2024-01-24 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0012_alter_property_area_name_alter_property_city_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='manager',
            new_name='managed_by',
        ),
        migrations.AddField(
            model_name='property',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_added_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
