# Generated by Django 4.2.3 on 2024-01-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0008_address'),
        ('hotels', '0014_rename_image_type_gallery_image_or_video_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='amenity',
            field=models.ManyToManyField(blank=True, help_text='Select amenities for this property.', related_name='property_amenities', to='org_resources.amenity'),
        ),
    ]
