# Generated by Django 4.2.3 on 2024-01-27 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_alter_property_amenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image_or_video_type',
        ),
    ]
