# Generated by Django 4.2.3 on 2024-01-27 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_resources', '0009_uploadedmedia'),
        ('hotels', '0016_remove_gallery_image_or_video_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='upload_image_or_video',
        ),
        migrations.AddField(
            model_name='gallery',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gallery',
            name='managed_by',
            field=models.ForeignKey(blank=True, help_text='Select a user as the gallery manager.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gallery',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='org_resources.uploadedmedia'),
        ),
    ]
