# Generated by Django 4.2.3 on 2024-02-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0020_inclusion_financialdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='franchise',
            field=models.BooleanField(default=False),
        ),
    ]
