# Generated by Django 4.2.3 on 2024-11-13 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0022_alter_property_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelAmenityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'HotelAmenity_Categories',
            },
        ),
        migrations.CreateModel(
            name='HotelAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('detail', models.JSONField(default={}, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amenity_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_amenity_category', to='hotels.hotelamenitycategory')),
            ],
            options={
                'verbose_name_plural': 'HotelAmenities',
            },
        ),
    ]
