# Generated by Django 4.2.3 on 2024-11-14 09:07

import IDBOOKAPI.utils
import apps.hotels.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0024_alter_hotelamenity_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'room', 'verbose_name_plural': 'rooms'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='amenity',
        ),
        migrations.RemoveField(
            model_name='property',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='no_of_floors',
        ),
        migrations.RemoveField(
            model_name='property',
            name='no_of_rooms',
        ),
        migrations.RemoveField(
            model_name='room',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='room',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='room',
            name='bed_count',
        ),
        migrations.RemoveField(
            model_name='room',
            name='carpet_area',
        ),
        migrations.RemoveField(
            model_name='room',
            name='child_capacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='person_capacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_for_12_hours',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_for_24_hours',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_for_4_hours',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_for_8_hours',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_per_night',
        ),
        migrations.AddField(
            model_name='property',
            name='amenity_details',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(blank=True, default='', help_text='Country where the property is located.', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, default='', help_text='State where the property is located.', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='amenity_details',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='end_availability_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='extra_bed_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='room',
            name='is_smoking_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='meal_options',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Name of the property.', max_length=70),
        ),
        migrations.AddField(
            model_name='room',
            name='no_available_rooms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='room_measurement_type',
            field=models.CharField(choices=[('square feet', 'square feet'), ('square meter', 'square meter')], default='', max_length=25),
        ),
        migrations.AddField(
            model_name='room',
            name='room_occupancy',
            field=models.JSONField(default=apps.hotels.models.default_room_occupancy_json),
        ),
        migrations.AddField(
            model_name='room',
            name='room_price',
            field=models.JSONField(default=apps.hotels.models.default_room_price_json),
        ),
        migrations.AddField(
            model_name='room',
            name='room_size',
            field=models.PositiveSmallIntegerField(default=0, help_text='Room Size'),
        ),
        migrations.AddField(
            model_name='room',
            name='start_availability_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hotelamenity',
            name='detail',
            field=models.JSONField(default=dict, help_text='{"choice": {"No": {"value": ""}, "Yes": {"value": "selected", "selectbox": {"Room controlled":{"value":""}, "Centralized":{"value":"selected"}}, "selectbox-1": ["All Weather(Hot & Cold)"]}}}', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.JSONField(default=IDBOOKAPI.utils.default_address_json),
        ),
        migrations.AlterField(
            model_name='property',
            name='area_name',
            field=models.CharField(blank=True, default='', help_text='Area name where the property is located.', max_length=60),
        ),
        migrations.AlterField(
            model_name='property',
            name='build_year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='chain_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='checkin_time',
            field=models.TimeField(help_text='Check-in time for the property.', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='checkout_time',
            field=models.TimeField(help_text='Check-out time for the property.', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='city_name',
            field=models.CharField(blank=True, default='', help_text='City name where the property is located.', max_length=35),
        ),
        migrations.AlterField(
            model_name='property',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='customer_care_no',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='property',
            name='email_list',
            field=models.JSONField(default=dict, help_text='["email 1", "email 2"]', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='no_of_restaurant',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='property',
            name='phone_no_list',
            field=models.JSONField(default=dict, help_text='["phone 1", "phone 2"]', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='starting_price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='vcc_currency',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='website_list',
            field=models.JSONField(default=dict, help_text='["website link 1", "website link 2"]', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_type',
            field=models.CharField(blank=True, choices=[('KING', 'KING'), ('QUEEN', 'QUEEN'), ('SINGLE', 'SINGLE')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='room',
            name='property',
            field=models.ForeignKey(help_text='Select the property this room belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_room', to='hotels.property'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, choices=[('DELUXE', 'DELUXE'), ('CLASSIC', 'CLASSIC'), ('PREMIUM', 'PREMIUM')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_view',
            field=models.CharField(blank=True, choices=[('SEA VIEW', 'DELUXE'), ('RIVER VIEW', 'CLASSIC'), ('VALLEY VIEW', 'PREMIUM')], default='', max_length=25),
        ),
    ]
