# Generated by Django 4.2.3 on 2024-11-15 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0026_roomamenitycategory_alter_hotelamenity_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelamenity',
            name='amenity_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_amenity', to='hotels.hotelamenitycategory'),
        ),
        migrations.AlterField(
            model_name='roomamenity',
            name='room_amenity_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_amenity', to='hotels.roomamenitycategory'),
        ),
    ]
