# Generated by Django 4.2.3 on 2024-11-18 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0027_alter_hotelamenity_amenity_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_view',
            field=models.CharField(blank=True, choices=[('SEA VIEW', 'SEA VIEW'), ('RIVER VIEW', 'RIVER VIEW'), ('VALLEY VIEW', 'VALLEY VIEW')], default='', max_length=25),
        ),
        migrations.CreateModel(
            name='RoomGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(null=True, upload_to='hotels/room/media/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_room', to='hotels.room')),
            ],
            options={
                'verbose_name_plural': 'RoomGallery',
            },
        ),
    ]
