# Generated by Django 4.2.3 on 2024-11-18 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0028_alter_room_room_view_roomgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomgallery',
            name='featured_image',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PropertyGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, upload_to='hotels/property/media/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('featured_image', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_property', to='hotels.property')),
            ],
            options={
                'verbose_name_plural': 'PropertyGallery',
            },
        ),
    ]
