# Generated by Django 4.2.3 on 2024-11-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0029_roomgallery_featured_image_propertygallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertygallery',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
