# Generated by Django 4.2.3 on 2024-11-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0031_remove_property_checkin_24_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='legal_documents',
            new_name='legal_document',
        ),
    ]
