# Generated by Django 4.2.3 on 2024-11-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0035_property_property_type_property_rental_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_extra_bed_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='extra_bed_type',
            field=models.CharField(blank=True, choices=[('Mattress', 'Mattress'), ('Cot', 'Cot'), ('Sofa cum bed', 'Sofa cum bed')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='room',
            name='meal_options',
            field=models.CharField(blank=True, choices=[('Accomodation only', 'Accomodation only'), ('Free Breakfast', 'Free Breakfast'), ('Free Breakfast and Lunch', 'Free Breakfast and Lunch'), ('Free Breakfast and Dinner', 'Free Breakfast and Dinner'), ('Free Breakfast, Lunch and Dinner', 'Free Breakfast, Lunch and Dinner'), ('Free Breakfast, Lunch, Dinner and Custom Inclusions', 'Free Breakfast, Lunch, Dinner and Custom Inclusions')], default='', max_length=100),
        ),
    ]
