# Generated by Django 4.2.3 on 2024-11-30 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0036_room_is_extra_bed_available_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
