# Generated by Django 4.2.3 on 2024-12-18 05:41

import apps.hotels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0038_propertybankdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='display_name',
        ),
        migrations.AddField(
            model_name='property',
            name='additional_fields',
            field=models.JSONField(default=apps.hotels.models.default_property_additional_fields_json, help_text='Additional Fields related to the property', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='review_count',
            field=models.PositiveIntegerField(default=0, help_text='Total Reviews'),
        ),
        migrations.AddField(
            model_name='property',
            name='review_star',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Review Rating of the property.', max_digits=3),
        ),
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Display name of the property.', max_length=200),
        ),
    ]
