# Generated by Django 4.2.3 on 2025-01-06 04:15

import apps.hotels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0039_remove_property_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='starting_price_details',
            field=models.JSONField(default=apps.hotels.models.default_starting_price_json, null=True),
        ),
    ]
