# Generated by Django 4.2.3 on 2025-01-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0041_property_is_slot_price_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_measurement_type',
            field=models.CharField(choices=[('square feet', 'square feet'), ('square meter', 'square meter')], default='', max_length=25),
        ),
        migrations.AddField(
            model_name='property',
            name='property_size',
            field=models.PositiveSmallIntegerField(default=0, help_text='Room Size'),
        ),
    ]
