# Generated by Django 4.2.3 on 2025-01-11 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0042_property_property_measurement_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_blocked_rooms', models.PositiveSmallIntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('blocked_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_property', to='hotels.property')),
                ('blocked_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_room', to='hotels.room')),
            ],
            options={
                'verbose_name_plural': 'BlockedProperty',
            },
        ),
    ]
