# Generated by Django 4.2.3 on 2025-01-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0043_blockedproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedproperty',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blockedproperty',
            name='is_entire_property',
            field=models.BooleanField(default=False),
        ),
    ]
