# Generated by Django 4.2.3 on 2025-01-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0044_blockedproperty_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.BigIntegerField()),
                ('room_id', models.BigIntegerField()),
                ('no_unavailable_rooms', models.PositiveSmallIntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
