# Generated by Django 4.2.3 on 2025-02-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0046_policydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_view',
            field=models.CharField(blank=True, choices=[('SEA VIEW', 'SEA VIEW'), ('RIVER VIEW', 'RIVER VIEW'), ('VALLEY VIEW', 'VALLEY VIEW'), ('CITY VIEW', 'CITY VIEW'), ('POOL VIEW', 'POOL VIEW'), ('BEACH VIEW', 'BEACH VIEW'), ('MOUNTAIN VIEW', 'MOUNTAIN VIEW'), ('LAKE VIEW', 'LAKE VIEW'), ('TEMPLE VIEW', 'TEMPLE VIEW'), ('GARDEN VIEW', 'GARDEN VIEW'), ('HILL VIEW', 'HILL VIEW'), ('NON VIEW', 'NON VIEW')], default='', max_length=25),
        ),
    ]
