# Generated by Django 4.2.3 on 2025-02-08 11:07

import apps.hotels.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0047_alter_room_room_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicRoomPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('room_price', models.JSONField(default=apps.hotels.models.default_room_price_json)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('for_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_dynamic_pricing', to='hotels.property')),
                ('for_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_dynamic_pricing', to='hotels.room')),
            ],
        ),
    ]
