# Generated by Django 4.2.3 on 2025-03-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0048_dynamicroompricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopDestinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=60)),
                ('display_name', models.CharField(max_length=60)),
                ('media', models.FileField(upload_to='hotels/top-destination/')),
                ('no_of_hotels', models.PositiveIntegerField(default=0, help_text='Total Hotel count for the location')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
