# Generated by Django 4.2.3 on 2025-03-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0052_alter_room_room_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_view',
            field=models.CharField(blank=True, choices=[('SEA VIEW', 'SEA VIEW'), ('RIVER VIEW', 'RIVER VIEW'), ('VALLEY VIEW', 'VALLEY VIEW'), ('CITY VIEW', 'CITY VIEW'), ('POOL VIEW', 'POOL VIEW'), ('SWIMMING POOL VIEW', 'SWIMMING POOL VIEW'), ('BEACH VIEW', 'BEACH VIEW'), ('MOUNTAIN VIEW', 'MOUNTAIN VIEW'), ('LAKE VIEW', 'LAKE VIEW'), ('TEMPLE VIEW', 'TEMPLE VIEW'), ('GARDEN VIEW', 'GARDEN VIEW'), ('HILL VIEW', 'HILL VIEW'), ('FOREST VIEW', 'FOREST VIEW'), ('TERRACE VIEW', 'TERRACE VIEW'), ('BALCONY VIEW', 'BALCONY VIEW'), ('JUNGLE VIEW', 'JUNGLE VIEW'), ('COURTYARD VIEW', 'COURTYARD VIEW'), ('NON VIEW', 'NON VIEW')], default='', max_length=25),
        ),
    ]
