# Generated by Django 4.2.3 on 2025-03-20 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0053_alter_room_room_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyLandmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landmark', models.CharField(help_text='Name of the landmark.', max_length=255)),
                ('distance', models.DecimalField(decimal_places=3, help_text='Distance from the property (in meters).', max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='landmark',
            field=models.ForeignKey(blank=True, help_text='Primary landmark for this property.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='properties', to='hotels.propertylandmark'),
        ),
    ]
