# Generated by Django 4.2.3 on 2025-03-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0054_propertylandmark_property_landmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='landmark',
        ),
        migrations.AddField(
            model_name='propertylandmark',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='hotels.property'),
        ),
    ]
