# Generated by Django 4.2.3 on 2025-03-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0056_unavailableproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='unavailableproperty',
            name='full_params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
