# Generated by Django 4.2.3 on 2025-03-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0057_unavailableproperty_full_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='maximum_no_of_nights',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='minimum_no_of_nights',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='no_of_banquets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='no_of_kitchen',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
