# Generated by Django 4.2.3 on 2025-03-27 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0058_property_maximum_no_of_nights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('commission_type', models.CharField(choices=[('AMOUNT', 'AMOUNT'), ('PERCENT', 'PERCENT')], max_length=20)),
                ('commission', models.DecimalField(decimal_places=6, max_digits=20)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('property_comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_commission', to='hotels.property')),
            ],
        ),
    ]
