# Generated by Django 4.2.3 on 2025-04-01 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0059_propertycommission'),
        ('hotels', '0059_trendingplaces'),
    ]

    operations = [
    ]
