# Generated by Django 4.2.3 on 2025-04-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0060_merge_0059_propertycommission_0059_trendingplaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertycommission',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
