# Generated by Django 4.2.3 on 2025-04-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0062_alter_property_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug for the property URL.', max_length=200, unique=True),
        ),
    ]
