# Generated by Django 4.2.3 on 2025-04-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0064_payathotelspendlimit_property_pay_at_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayathoteleligibility',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount spent by the user in a month', max_digits=10),
        ),
    ]
