# Generated by Django 4.2.3 on 2025-04-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0065_monthlypayathoteleligibility_spent_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payathotelspendlimit',
            name='cancel_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of cancellation for this booking range'),
        ),
        migrations.AddField(
            model_name='payathotelspendlimit',
            name='cancel_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum cancellation amount for this booking range', max_digits=10),
        ),
    ]
