# Generated by Django 4.2.3 on 2025-04-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0066_payathotelspendlimit_cancel_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayathoteleligibility',
            name='cancel_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Allowed cancel amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='monthlypayathoteleligibility',
            name='is_blacklisted',
            field=models.BooleanField(default=False, help_text='Is the user blacklisted this month?'),
        ),
        migrations.AddField(
            model_name='monthlypayathoteleligibility',
            name='total_cancel_count',
            field=models.PositiveIntegerField(default=0, help_text='Allowed cancel count', null=True),
        ),
        migrations.AddField(
            model_name='monthlypayathoteleligibility',
            name='updated_by',
            field=models.CharField(default='Automatic', help_text='Who updated this record?', max_length=50),
        ),
    ]
