# Generated by Django 4.2.3 on 2025-05-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0067_monthlypayathoteleligibility_cancel_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='discount_type',
            field=models.CharField(choices=[('AMOUNT', 'AMOUNT'), ('PERCENT', 'PERCENT')], default='PERCENT', max_length=20),
        ),
    ]
