# Generated by Django 4.2.3 on 2025-05-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0068_room_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_svc_agreement_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='verified_ip',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='property',
            name='verify_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
