# Generated by Django 4.2.3 on 2025-05-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0069_property_is_svc_agreement_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='service_agreement_pdf',
            field=models.FileField(blank=True, null=True, upload_to='hotels/service_agreements/'),
        ),
    ]
