# Generated by Django 4.2.3 on 2025-05-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0070_property_service_agreement_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='pay_at_hotel',
            field=models.BooleanField(default=True, help_text='If true, customer can pay at the hotel.'),
        ),
    ]
