# Generated by Django 4.2.3 on 2025-05-13 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0071_alter_property_pay_at_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPayoutDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('pg_ref_no', models.CharField(blank=True, max_length=100)),
                ('payment_type', models.CharField(blank=True, max_length=50)),
                ('initiate_status', models.PositiveSmallIntegerField(null=True)),
                ('initiate_message', models.CharField(blank=True, max_length=200)),
                ('initiate_response', models.JSONField(null=True)),
                ('initiate_date', models.DateTimeField(null=True)),
                ('transaction_response', models.JSONField(null=True)),
                ('paid', models.BooleanField(default=False)),
                ('transaction_status', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payout_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_payout', to='hotels.property')),
            ],
        ),
    ]
