# Generated by Django 4.2.3 on 2025-05-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0072_propertypayoutdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypayoutdetails',
            name='batch_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propertypayoutdetails',
            name='booking_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='propertypayoutdetails',
            name='payment_medium',
            field=models.CharField(choices=[('PHONE PAY', 'PHONE PAY'), ('PayU', 'PayU'), ('Idbook', 'Idbook'), ('Hotel', 'Hotel')], default='', max_length=50),
        ),
    ]
