# Generated by Django 4.2.3 on 2025-05-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0073_propertypayoutdetails_batch_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertypayoutdetails',
            old_name='payment_type',
            new_name='transaction_type',
        ),
        migrations.AddField(
            model_name='propertypayoutdetails',
            name='batch_created_by',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('AUTO', 'AUTO')], max_length=20),
        ),
        migrations.AddField(
            model_name='propertypayoutdetails',
            name='payout_reference_file',
            field=models.FileField(blank=True, null=True, upload_to='hotels/payout/transaction/'),
        ),
        migrations.AddField(
            model_name='propertypayoutdetails',
            name='transaction_executed_by',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('AUTO', 'AUTO')], max_length=20),
        ),
    ]
