# Generated by Django 4.2.3 on 2025-05-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0074_rename_payment_type_propertypayoutdetails_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypayoutdetails',
            name='payment_medium',
            field=models.CharField(choices=[('PHONE PAY', 'PHONE PAY'), ('PayU', 'PayU'), ('Idbook', 'Idbook'), ('Hotel', 'Hotel'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('UPI', 'UPI'), ('NET_BANKING', 'Net Banking'), ('Others', 'Others')], default='', max_length=50),
        ),
    ]
