# Generated by Django 4.2.3 on 2025-06-06 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0075_alter_propertypayoutdetails_payment_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='payathotelspendlimit',
            name='pro_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payathotelspendlimit',
            name='pro_spend_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payathotelspendlimit',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotels.property', verbose_name='booking_property'),
        ),
        migrations.AddField(
            model_name='payathotelspendlimit',
            name='property_spend_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
