# Generated by Django 4.2.3 on 2025-11-13 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.PositiveIntegerField(help_text='otp')),
                ('otp_type', models.CharField(choices=[('MOBILE', 'MOBILE'), ('EMAIL', 'EMAIL')], default='EMAIL', help_text='otp generated medium', max_length=25)),
                ('user_account', models.CharField(help_text='Email or Mobile Number', max_length=100)),
                ('otp_for', models.CharField(choices=[('LOGIN', 'LOGIN'), ('SIGNUP', 'SIGNUP'), ('VERIFY', 'VERIFY'), ('VERIFY-GUEST', 'VERIFY-GUEST'), ('PASSWORD-RESET', 'PASSWORD-RESET'), ('OTHER', 'OTHER')], default='OTHER', max_length=25)),
                ('otp_generate_tries', models.PositiveIntegerField(default=1, help_text='Number of OTP generation attempts')),
                ('login_tries', models.PositiveIntegerField(default=0, help_text='Number of OTP login attempts')),
                ('pwd_reset_tries', models.PositiveIntegerField(default=0, help_text='Number of password reset OTP attempts')),
                ('verify_tries', models.PositiveIntegerField(default=0, help_text='Number of signup OTP verification attempts')),
                ('last_attempt_time', models.DateTimeField(auto_now=True, help_text='Last OTP generation attempt time')),
                ('last_login_attempt_time', models.DateTimeField(blank=True, help_text='Last OTP login attempt time', null=True)),
                ('last_pwd_reset_attempt_time', models.DateTimeField(blank=True, help_text='Last password reset OTP attempt time', null=True)),
                ('last_verify_attempt_time', models.DateTimeField(blank=True, help_text='Last signup OTP verification attempt time', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the role.', max_length=50, unique=True)),
                ('short_code', models.CharField(db_index=True, default='', help_text='Short code representing the role.', max_length=3, unique=True)),
                ('permissions', models.ManyToManyField(help_text='Select permissions associated with this role.', to='auth.permission')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Email address of the user.', max_length=254, null=True, validators=[django.core.validators.EmailValidator])),
                ('mobile_number', models.CharField(blank=True, db_index=True, help_text='Mobile number of the user (10 digits only).', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('name', models.CharField(blank=True, help_text='Name of the user.', max_length=30, null=True)),
                ('first_name', models.CharField(blank=True, help_text='First name of the user.', max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Last name of the user.', max_length=30, null=True)),
                ('referral', models.CharField(blank=True, help_text='Referral code associated with the user.', max_length=120)),
                ('referred_code', models.CharField(blank=True, help_text='Referred by user code.', max_length=120)),
                ('custom_id', models.CharField(blank=True, db_index=True, help_text='Custom ID for the user.', max_length=15)),
                ('category', models.CharField(blank=True, help_text='Category of the user.', max_length=20)),
                ('business_id', models.BigIntegerField(blank=True, help_text='Business detail id', null=True)),
                ('company_id', models.BigIntegerField(blank=True, help_text='company detail id', null=True)),
                ('first_booking', models.BooleanField(default=False, help_text='Status for first confirmed booking')),
                ('email_verified', models.BooleanField(default=False, help_text="Whether the user's email address is verified.")),
                ('mobile_verified', models.BooleanField(default=False, help_text="Whether the user's mobile number is verified.")),
                ('is_active', models.BooleanField(default=True, help_text='Whether the user account is active.')),
                ('is_staff', models.BooleanField(default=False, help_text='Whether the user has staff privileges.')),
                ('default_group', models.CharField(help_text='Switched group', max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time when the user account was created.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date and time when the user account was last updated.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('roles', models.ManyToManyField(blank=True, help_text='Select roles associated with this user.', related_name='user_role', to='authentication.role')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
