# Generated by Django 4.2.3 on 2026-01-05 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("org_managements", "0002_alter_businessdetail_options"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Region code for region-based access (e.g., TN, KA).",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "association_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Association ID for association-based access (company_id, hotel_id, or agent_id).",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this role assignment is active.",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this role was assigned."
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Role Assignment",
                "verbose_name_plural": "User Role Assignments",
                "ordering": ("-assigned_at",),
            },
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ("name",)},
        ),
        migrations.AddField(
            model_name="role",
            name="business",
            field=models.ForeignKey(
                blank=True,
                help_text="Business this role belongs to. Null for system roles.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="org_managements.businessdetail",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="role",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Django Group this role belongs to (e.g., BUSINESS-GRP, CORPORATE-GRP).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="roles",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="is_system_role",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is a system role (BUS-ADMIN, CORP-ADMIN, etc.).",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(help_text="Name of the role.", max_length=50),
        ),
        migrations.AlterField(
            model_name="role",
            name="short_code",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="Short code representing the role.",
                max_length=3,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("name", "business")},
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["business", "is_system_role"],
                name="authenticat_busines_af05b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["group", "is_system_role"],
                name="authenticat_group_i_b7a079_idx",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who assigned this role.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="business",
            field=models.ForeignKey(
                help_text="Business this role assignment belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to="org_managements.businessdetail",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="role",
            field=models.ForeignKey(
                help_text="Role assigned to the user.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to="authentication.role",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="user",
            field=models.ForeignKey(
                help_text="User this role is assigned to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["user", "business", "is_active"],
                name="authenticat_user_id_bbe412_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["user", "association_id", "is_active"],
                name="authenticat_user_id_d67b45_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["business", "is_active"], name="authenticat_busines_1f161d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together={("user", "role", "business", "association_id")},
        ),
    ]
