# Generated by Django 4.2.3 on 2026-01-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_userrole_alter_role_options_role_business_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Detailed description of what this role does and its responsibilities.",
                null=True,
            ),
        ),
    ]
