# Generated by Django 4.2.3 on 2026-01-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org_managements", "0002_alter_businessdetail_options"),
        ("authentication", "0003_role_description"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("name", "business", "is_system_role")},
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["name", "is_system_role"], name="authenticat_name_415569_idx"
            ),
        ),
    ]
