# Generated by Django 4.2.3 on 2024-09-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Select roles associated with this user.', related_name='user_role', to='authentication.role'),
        ),
    ]
