# Generated by Django 4.2.3 on 2024-10-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.PositiveIntegerField(help_text='otp')),
                ('otp_type', models.CharField(choices=[('MOBILE', 'MOBILE'), ('EMAIL', 'EMAIL')], default='EMAIL', help_text='otp generated medium', max_length=25)),
                ('user_account', models.CharField(help_text='Email or Mobile Number', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
