# Generated by Django 4.2.3 on 2024-10-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_id',
            field=models.BigIntegerField(blank=True, help_text='Business detail id', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_id',
            field=models.BigIntegerField(blank=True, help_text='company detail id', null=True),
        ),
    ]
