# Generated by Django 4.2.3 on 2024-10-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_business_id_user_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the user.', max_length=30, null=True),
        ),
    ]
