# Generated by Django 4.2.3 on 2024-11-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_booking',
            field=models.BooleanField(default=False, help_text='Status for first confirmed booking'),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_code',
            field=models.CharField(blank=True, help_text='Referred by user code.', max_length=120),
        ),
    ]
