# Generated by Django 4.2.3 on 2024-11-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_first_booking_user_referred_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_group',
            field=models.CharField(help_text='Switched group', max_length=30, null=True),
        ),
    ]
