# Generated by Django 4.2.3 on 2025-01-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_default_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='otp_for',
            field=models.CharField(choices=[('LOGIN', 'LOGIN'), ('SIGNUP', 'SIGNUP'), ('VERIFY', 'VERIFY'), ('OTHER', 'OTHER')], default='OTHER', max_length=25),
        ),
    ]
