# Generated by Django 4.2.3 on 2025-03-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_userotp_otp_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp_for',
            field=models.CharField(choices=[('LOGIN', 'LOGIN'), ('SIGNUP', 'SIGNUP'), ('VERIFY', 'VERIFY'), ('VERIFY-GUEST', 'VERIFY-GUEST'), ('OTHER', 'OTHER')], default='OTHER', max_length=25),
        ),
    ]
