# Generated by Django 4.2.3 on 2025-05-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_userotp_otp_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='last_attempt_time',
            field=models.DateTimeField(auto_now=True, help_text='Last OTP generation attempt time'),
        ),
        migrations.AddField(
            model_name='userotp',
            name='otp_generate_tries',
            field=models.PositiveIntegerField(default=1, help_text='Number of OTP generation attempts'),
        ),
    ]
