# Generated by Django 4.2.3 on 2025-05-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_userotp_last_attempt_time_userotp_otp_generate_tries'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='last_login_attempt_time',
            field=models.DateTimeField(blank=True, help_text='Last OTP login attempt time', null=True),
        ),
        migrations.AddField(
            model_name='userotp',
            name='login_tries',
            field=models.PositiveIntegerField(default=0, help_text='Number of OTP login attempts'),
        ),
    ]
