# Generated by Django 4.2.3 on 2025-05-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_userotp_last_login_attempt_time_userotp_login_tries'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='last_pwd_reset_attempt_time',
            field=models.DateTimeField(blank=True, help_text='Last password reset OTP attempt time', null=True),
        ),
        migrations.AddField(
            model_name='userotp',
            name='pwd_reset_tries',
            field=models.PositiveIntegerField(default=0, help_text='Number of password reset OTP attempts'),
        ),
    ]
