# Generated by Django 4.2.3 on 2025-05-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_userotp_last_pwd_reset_attempt_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp_for',
            field=models.CharField(choices=[('LOGIN', 'LOGIN'), ('SIGNUP', 'SIGNUP'), ('VERIFY', 'VERIFY'), ('VERIFY-GUEST', 'VERIFY-GUEST'), ('PASSWORD-RESET', 'PASSWORD-RESET'), ('OTHER', 'OTHER')], default='OTHER', max_length=25),
        ),
    ]
