# Generated by Django 4.2.3 on 2025-05-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_userotp_otp_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='last_verify_attempt_time',
            field=models.DateTimeField(blank=True, help_text='Last signup OTP verification attempt time', null=True),
        ),
        migrations.AddField(
            model_name='userotp',
            name='verify_tries',
            field=models.PositiveIntegerField(default=0, help_text='Number of signup OTP verification attempts'),
        ),
    ]
