# Generated by Django 4.2.3 on 2025-11-13 07:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTourEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator])),
                ('mobile_number', models.CharField(db_index=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('tour_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('tour_start_date', models.DateField()),
                ('tour_end_date', models.DateField()),
                ('tour_duration', models.CharField(help_text='enter duration like 4N/5D', max_length=50)),
                ('date_of_journey', models.DateField()),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('tour_start_city', models.CharField(max_length=50)),
                ('flight_required', models.BooleanField(default=False)),
                ('private_transfer', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator])),
                ('mobile_number', models.CharField(db_index=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=15, null=True)),
                ('repeat_account_number', models.CharField(blank=True, max_length=15, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=15, null=True)),
                ('paytm_number', models.CharField(blank=True, max_length=10, null=True)),
                ('google_pay_number', models.CharField(blank=True, max_length=10, null=True)),
                ('phonepe_number', models.CharField(blank=True, max_length=10, null=True)),
                ('upi', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(blank=True, db_index=True, max_length=10)),
                ('trip_name', models.CharField(blank=True, max_length=50)),
                ('customer_fullname', models.CharField(max_length=50)),
                ('tour_duration', models.CharField(choices=[('1N/2D', '1N/2D'), ('2N/3D', '2N/3D'), ('3N/4D', '3N/4D'), ('4N/5D', '4N/5D'), ('5N/6D', '5N/6D'), ('6N/7D', '6N/7D'), ('7N/8D', '7N/8D'), ('8N/9D', '8N/9D'), ('9N/10D', '9N/10D'), ('10N/11D', '10N/11D'), ('11N/12D', '11N/12D'), ('12N/13D', '12N/13D'), ('13N/13D', '13N/14D'), ('14N/13D', '14N/15D'), ('15N/13D', '15N/16D'), ('16N/13D', '16N/17D'), ('17N/13D', '17N/18D')], default=1, max_length=50)),
                ('date_of_journey', models.DateField()),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('tour_start_city', models.CharField(max_length=50)),
                ('total_booking_amount', models.FloatField(default=0)),
                ('advance_amount_to_pay_for_the_trip_confirmation', models.CharField(max_length=50)),
                ('payment_link', models.URLField(blank=True, default='', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, max_length=50)),
                ('no_of_room', models.PositiveSmallIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('occupancy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='occupancy_detail', to='org_resources.occupancy')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_type', to='org_resources.roomtype')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tour_accommodation', to='holiday_package.tourpackage')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tour_vehicle', to='holiday_package.tourpackage')),
            ],
            options={
                'unique_together': {('tour', 'vehicle_type')},
            },
        ),
        migrations.CreateModel(
            name='InclusionExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('INCLUSION', 'Inclusion'), ('EXCLUSION', 'Exclusion')], default='INCLUSION', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tour_inclusion_and_exclusion', to='holiday_package.tourpackage')),
            ],
            options={
                'unique_together': {('tour', 'status')},
            },
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('plan_date', models.DateField()),
                ('stay', models.CharField(max_length=50)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('detailed_plan', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tour_daily_plan', to='holiday_package.tourpackage')),
            ],
            options={
                'unique_together': {('tour', 'title')},
            },
        ),
    ]
