# Generated by Django 4.2.3 on 2023-07-17 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_resources', '0004_occupancy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, unique=True)),
                ('plan_date', models.DateField()),
                ('stay', models.CharField(max_length=50)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('detailed_plan', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InclusionExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('INCLUSION', 'INCLUSION'), ('EXCLUSION', 'EXCLUSION')], default='INCLUSION', max_length=50, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=10)),
                ('trip_name', models.CharField(max_length=50, unique=True)),
                ('short_code', models.CharField(db_index=True, default='', max_length=10, unique=True)),
                ('customer_fullname', models.CharField(max_length=50)),
                ('tour_duration', models.CharField(help_text='enter duration like 4N/5D', max_length=50)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('date_of_journey', models.DateField()),
                ('tour_company', models.CharField(max_length=50)),
                ('company_location', models.CharField(max_length=50)),
                ('company_phone', models.CharField(max_length=50)),
                ('company_email', models.CharField(max_length=50)),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('tour_start_city', models.CharField(max_length=50)),
                ('total_booking_amount', models.FloatField(default=0)),
                ('advance_amount_to_pay_for_the_trip_confirmation', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='executive', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=50, unique=True)),
                ('no_of_room', models.PositiveSmallIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('occupancy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='occupancy_detail', to='org_resources.occupancy')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_type', to='org_resources.roomtype')),
            ],
        ),
    ]
