# Generated by Django 4.2.3 on 2026-03-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='executive',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
