# Generated by Django 4.2.3 on 2023-07-17 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_package', '0002_rename_trippackage_tourpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tour_accommodation', to='holiday_package.tourpackage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tour_daily_plan', to='holiday_package.tourpackage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inclusionexclusion',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tour_inclusion_and_exclusion', to='holiday_package.tourpackage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tour_vehicle', to='holiday_package.tourpackage'),
            preserve_default=False,
        ),
    ]
