# Generated by Django 4.2.3 on 2023-07-18 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_package', '0005_tourbankdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTourEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator])),
                ('mobile_number', models.CharField(db_index=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('tour_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('tour_start_date', models.DateField()),
                ('tour_end_date', models.DateField()),
                ('tour_duration', models.CharField(help_text='enter duration like 4N/5D', max_length=50)),
                ('date_of_journey', models.DateField()),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('tour_start_city', models.CharField(max_length=50)),
                ('flight_required', models.BooleanField(default=False)),
                ('private_transfer', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
