# Generated by Django 4.2.3 on 2023-07-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_package', '0007_remove_tourpackage_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='tour_duration',
            field=models.CharField(choices=[(1, '1N/2D'), (2, '2N/3D'), (3, '3N/4D'), (4, '4N/5D'), (5, '5N/6D'), (6, '6N/7D'), (7, '7N/8D'), (8, '8N/9D'), (9, '9N/10D'), (10, '10N/11D'), (11, '11N/12D'), (12, '12N/13D'), (13, '13N/14D'), (14, '14N/15D'), (15, '15N/16D'), (16, '16N/17D'), (17, '17N/18D')], default=1, max_length=50),
        ),
    ]
