# Generated by Django 4.2.3 on 2023-07-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_package', '0008_alter_tourpackage_tour_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='short_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='trip_id',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
