# Generated by Django 4.2.3 on 2023-07-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_package', '0009_alter_tourpackage_short_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='trip_id',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
    ]
