# Generated by Django 4.2.3 on 2023-07-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_package', '0010_alter_tourpackage_trip_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='short_code',
        ),
    ]
