# Generated by Django 4.2.3 on 2023-07-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_package', '0011_remove_tourpackage_short_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyplan',
            unique_together={('tour', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='inclusionexclusion',
            unique_together={('tour', 'status')},
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('tour', 'vehicle_type')},
        ),
    ]
