# Generated by Django 4.2.3 on 2023-07-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_package', '0012_alter_dailyplan_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusionexclusion',
            name='status',
            field=models.CharField(choices=[('INCLUSION', 'INCLUSION'), ('EXCLUSION', 'EXCLUSION')], default='INCLUSION', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(max_length=50),
        ),
    ]
