# Generated by Django 4.2.3 on 2023-07-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_package', '0013_alter_inclusionexclusion_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyplan',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
