# Generated by Django 4.2.3 on 2023-07-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_package', '0014_alter_dailyplan_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='payment_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
