# Generated by Django 4.2.3 on 2023-07-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_package', '0015_tourpackage_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='trip_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
