# Generated by Django 4.2.3 on 2023-07-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_package', '0017_alter_accommodation_hotel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='payment_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
