# Generated by Django 4.2.3 on 2023-08-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_package', '0018_alter_tourpackage_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclusionexclusion',
            name='status',
            field=models.CharField(choices=[('INCLUSION', 'Inclusion'), ('EXCLUSION', 'Exclusion')], default='INCLUSION', max_length=50),
        ),
    ]
