# Generated by Django 4.2.3 on 2024-10-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_package', '0019_alter_inclusionexclusion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='tour_duration',
            field=models.CharField(choices=[('1N/2D', '1N/2D'), ('2N/3D', '2N/3D'), ('3N/4D', '3N/4D'), ('4N/5D', '4N/5D'), ('5N/6D', '5N/6D'), ('6N/7D', '6N/7D'), ('7N/8D', '7N/8D'), ('8N/9D', '8N/9D'), ('9N/10D', '9N/10D'), ('10N/11D', '10N/11D'), ('11N/12D', '11N/12D'), ('12N/13D', '12N/13D'), ('13N/13D', '13N/14D'), ('14N/13D', '14N/15D'), ('15N/13D', '15N/16D'), ('16N/13D', '16N/17D'), ('17N/13D', '17N/18D')], default=1, max_length=50),
        ),
    ]
