# Generated by Django 4.2.3 on 2024-10-24 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'CAR'), ('TRAVELLER', 'TRAVELLER'), ('BUS', 'BUS')], default='CAR', help_text='vehicle type.', max_length=25)),
                ('vehicle_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('driver_name', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(blank=True, help_text='Email address of the vehicle driver.', max_length=254, null=True, validators=[django.core.validators.EmailValidator])),
                ('contact_number', models.CharField(help_text='Mobile number of the vehicle driver (10 digits only).', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
