# Generated by Django 4.2.3 on 2025-12-16 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0004_alter_flightpassenger_date_of_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=50, null=True)),
                ("enabled", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payment_gateways_paymentgateway",
            },
        ),
        migrations.CreateModel(
            name="RazorpayPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razorpay_customer_id", models.CharField(blank=True, max_length=50)),
                ("razorpay_order_id", models.CharField(blank=True, max_length=50)),
                ("razorpay_payment_id", models.CharField(blank=True, max_length=50)),
                ("razorpay_contact_id", models.CharField(blank=True, max_length=50)),
                (
                    "razorpay_vpa_fund_account_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "razorpay_bank_fund_account_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("razorpay_payout_id", models.CharField(blank=True, max_length=50)),
                (
                    "razorpay_transaction_id",
                    models.CharField(blank=True, max_length=50),
                ),
                ("razorpay_utr_no", models.CharField(blank=True, max_length=50)),
                ("entity", models.CharField(blank=True, max_length=50, null=True)),
                ("mode", models.CharField(blank=True, max_length=50, null=True)),
                ("amount", models.FloatField(default=0)),
                ("currency", models.CharField(max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="razorpay_payout_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_gateways_razorpaypayout",
            },
        ),
        migrations.CreateModel(
            name="RazorpayOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rp_id", models.CharField(max_length=250)),
                ("entity", models.CharField(max_length=50)),
                ("amount", models.PositiveIntegerField(default=0)),
                ("amount_due", models.PositiveIntegerField(default=0)),
                ("currency", models.CharField(default="INR", max_length=50)),
                ("receipt", models.CharField(blank=True, max_length=50, null=True)),
                ("offer_id", models.CharField(blank=True, max_length=50, null=True)),
                ("status", models.CharField(max_length=50)),
                ("payment_id", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "payment_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("notes", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.CharField(blank=True, max_length=50, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="razorpay_orders",
                        to="booking.booking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="razorpay_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_gateways_razorpayorder",
                "ordering": ["-created"],
            },
        ),
    ]
