# Generated by Django 4.2.3 on 2026-03-17 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_group_type', models.CharField(blank=True, choices=[('GUEST', 'Guest'), ('B2C', 'B2C User'), ('CORPORATE', 'Corporate User'), ('AGENT', 'Agent'), ('HOTELIER', 'Hotelier'), ('BUSINESS_STAFF', 'Business Staff')], help_text='If empty, applies to all groups (filtered via target_filters).', max_length=32)),
                ('target_filters', models.JSONField(blank=True, default=dict, help_text='Flexible filters: {"city": "Kochi", "country": "INDIA"}')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=32)),
                ('schedule_time', models.DateTimeField(blank=True, help_text='If set, initial campaign dispatch will be scheduled for this time.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(help_text='Ordering of steps within a campaign (1,2,3...).')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=16)),
                ('template_code', models.CharField(blank=True, help_text='For SMS: MessageTemplate.template_code; for Email: EmailTemplate.slug.', max_length=255)),
                ('delay_amount', models.PositiveIntegerField(default=0, help_text='Delay after previous step (or campaign start) before sending.')),
                ('delay_unit', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], default='hours', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='messaging.campaign')),
            ],
            options={
                'ordering': ['campaign', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('group_type', models.CharField(choices=[('GUEST', 'Guest'), ('B2C', 'B2C User'), ('CORPORATE', 'Corporate User'), ('AGENT', 'Agent'), ('HOTELIER', 'Hotelier'), ('BUSINESS_STAFF', 'Business Staff')], db_index=True, max_length=32)),
                ('segment_tags', models.JSONField(blank=True, default=list)),
                ('remarks', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, db_index=True, max_length=128)),
                ('opt_out_sms', models.BooleanField(default=False)),
                ('opt_out_email', models.BooleanField(default=False)),
                ('opt_out_whatsapp', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, help_text='e.g. excel_upload', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaging_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessagingProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('is_default', models.BooleanField(default=False, help_text='If true, this config will be used when no explicit provider is selected.')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Provider specific settings (API key overrides, sender IDs, etc.)')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=0, help_text='Soft rate limit hint for this provider (0 = use system default).')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('channel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], max_length=16)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='messaging.campaign')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='messaging.contact')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='messaging.campaignstep')),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField(blank=True)),
                ('variables_schema', models.JSONField(blank=True, default=list, help_text="List of supported variables, e.g. ['name', 'city', 'booking_link']")),
                ('is_marketing', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_templates', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, limit_choices_to={'channel': 'email'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.messagingproviderconfig')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=32)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('error_report_path', models.CharField(blank=True, help_text='Path to stored error report file', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped_opt_out', 'Skipped (opt-out)'), ('blacklisted', 'Skipped (blacklisted)')], default='pending', max_length=32)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When this specific message is scheduled to be sent.', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_contacts', to='messaging.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_contacts', to='messaging.contact')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_contacts', to='messaging.campaignstep')),
            ],
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['group_type', 'city'], name='messaging_c_group_t_5507f0_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['group_type', 'country'], name='messaging_c_group_t_330af4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignstep',
            unique_together={('campaign', 'order_index')},
        ),
        migrations.AlterUniqueTogether(
            name='campaigncontact',
            unique_together={('campaign', 'step', 'contact')},
        ),
    ]
