# Generated by Django 4.2.3 on 2026-03-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_contact_group_type_use_auth_constants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="target_group_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("B2C-GRP", "B2C User"),
                    ("B2C-GUEST", "Guest"),
                    ("CORP-ADMIN", "Corporate Admin"),
                    ("CORP-EMP", "Corporate Employee"),
                    ("CORPORATE-GRP", "Corporate"),
                    ("BUSINESS-GRP", "Business"),
                    ("BUS-ADMIN", "Business Admin"),
                    ("HTLR-ADMIN", "Hotelier Admin"),
                    ("FRANCH-ADMIN", "Franchise Admin"),
                    ("HOTELIER-GRP", "Hotelier"),
                    ("FRANCHISE-GRP", "Franchise"),
                    ("AGENT-GRP", "Agent"),
                    ("AGENT-ADMIN", "Agent Admin"),
                ],
                help_text="If empty, applies to all groups (filtered via target_filters).",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="group_type",
            field=models.CharField(
                choices=[
                    ("B2C-GRP", "B2C User"),
                    ("B2C-GUEST", "Guest"),
                    ("CORP-ADMIN", "Corporate Admin"),
                    ("CORP-EMP", "Corporate Employee"),
                    ("CORPORATE-GRP", "Corporate"),
                    ("BUSINESS-GRP", "Business"),
                    ("BUS-ADMIN", "Business Admin"),
                    ("HTLR-ADMIN", "Hotelier Admin"),
                    ("FRANCH-ADMIN", "Franchise Admin"),
                    ("HOTELIER-GRP", "Hotelier"),
                    ("FRANCHISE-GRP", "Franchise"),
                    ("AGENT-GRP", "Agent"),
                    ("AGENT-ADMIN", "Agent Admin"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="contactuploadsession",
            name="error_report_path",
            field=models.TextField(
                blank=True,
                help_text="JSON array of row errors, or path to stored error report file",
            ),
        ),
    ]
