# Generated by Django 4.2.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0003_contact_upload_session_error_report_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactuploadsession",
            name="created_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of contacts newly created",
            ),
        ),
        migrations.AddField(
            model_name="contactuploadsession",
            name="updated_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of rows that matched existing contacts (updated)",
            ),
        ),
    ]
