# Generated by Django 4.2.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0004_contactuploadsession_created_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactuploadsession",
            name="duplicate_in_file_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of rows in the CSV that were duplicates (same group_type+phone/email seen earlier in file)",
            ),
        ),
    ]
