# Generated by Django 4.2.3 on 2023-08-17 10:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0010_remove_property_country_remove_property_district_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('4 HOURS', 4), ('8 HOURS', 8), ('12 HOURS', 12), ('24 HOURS', 24)], default='24 HOURS', help_text='booking type.', max_length=25)),
                ('room_type', models.CharField(choices=[('DELUXE', 'DELUXE'), ('CLASSIC', 'CLASSIC'), ('PREMIUM', 'PREMIUM')], default='DELUXE', help_text='booked room type.', max_length=25)),
                ('checkin_time', models.DateField(help_text='Check-in time for the property.')),
                ('checkout_time', models.DateField(help_text='Check-out time for the property.')),
                ('bed_count', models.PositiveIntegerField(default=1, help_text='bed count')),
                ('person_capacity', models.PositiveSmallIntegerField(default=1, help_text='adults count')),
                ('child_capacity', models.PositiveSmallIntegerField(default=0, help_text='children count')),
                ('deal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.coupon', verbose_name='booking_coupon')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotels.property', verbose_name='booking_property')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotels.room', verbose_name='booking_room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='booking_user')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_applied_coupon', to='booking.booking')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_applied', to='coupons.coupon')),
            ],
        ),
    ]
