# Generated by Django 4.2.3 on 2025-11-13 07:17

import apps.booking.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hotels", "0001_initial"),
        ("org_managements", "0001_initial"),
        ("coupons", "0001_initial"),
        ("org_resources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vehicle_management", "0001_initial"),
        ("holiday_package", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "confirmation_code",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("invoice_id", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "booking_type",
                    models.CharField(
                        choices=[
                            ("HOLIDAYPACK", "HOLIDAYPACK"),
                            ("HOTEL", "HOTEL"),
                            ("VEHICLE", "VEHICLE"),
                            ("FLIGHT", "FLIGHT"),
                        ],
                        default="HOTEL",
                        help_text="booking type.",
                        max_length=25,
                    ),
                ),
                (
                    "adult_count",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="adults count"
                    ),
                ),
                (
                    "child_count",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="children count"
                    ),
                ),
                ("child_age_list", models.JSONField(default=list, null=True)),
                (
                    "infant_count",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="infant count"
                    ),
                ),
                (
                    "coupon_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=6, default=0, max_digits=15),
                ),
                (
                    "pro_member_discount_percent",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Discount percent for pro member"
                    ),
                ),
                (
                    "pro_member_discount_value",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Discount value"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.0,
                        help_text="Price for the booking",
                        max_digits=20,
                    ),
                ),
                (
                    "gst_percentage",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.0,
                        help_text="GST % for the booking",
                        max_digits=20,
                    ),
                ),
                (
                    "gst_amount",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.0,
                        help_text="GST amount for the booking",
                        max_digits=20,
                    ),
                ),
                (
                    "gst_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", ""),
                            ("IGST", "IGST"),
                            ("CGST/SGST", "CGST/SGST"),
                        ],
                        default="",
                        help_text="GST Type",
                        max_length=25,
                    ),
                ),
                (
                    "service_tax",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.0,
                        help_text="Service tax for the booking",
                        max_digits=20,
                    ),
                ),
                (
                    "total_discount",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Total discount of a booking",
                        max_digits=20,
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Final amount after considering gst, discount",
                        max_digits=20,
                    ),
                ),
                (
                    "total_payment_made",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.0,
                        help_text="Total Payment made",
                        max_digits=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("canceled", "Canceled"),
                            ("completed", "Completed"),
                            ("no_show", "No Show"),
                            ("on_hold", "On Hold"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                ("on_hold_end_time", models.DateTimeField(null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("additional_notes", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                ("is_reviewed", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "is_checkin",
                    models.BooleanField(default=False, help_text="Check_in status"),
                ),
                (
                    "is_checkout",
                    models.BooleanField(default=False, help_text="Check_out status"),
                ),
                ("is_direct_pay", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="org_resources.companydetail",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="coupons.coupon",
                        verbose_name="booking_coupon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlightBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_no", models.CharField(blank=True, default="", max_length=50)),
                (
                    "airline_code",
                    models.CharField(
                        blank=True,
                        help_text="Airline code (e.g., 6E, UK)",
                        max_length=3,
                    ),
                ),
                (
                    "flight_trip",
                    models.CharField(
                        choices=[("ONE-WAY", "ONE-WAY"), ("ROUND", "ROUND")],
                        default="ROUND",
                        help_text="flight trip (one-way or round).",
                        max_length=25,
                    ),
                ),
                (
                    "flight_class",
                    models.CharField(
                        choices=[
                            ("ECONOMY", "ECONOMY"),
                            ("BUSINESS", "BUSINESS"),
                            ("FIRST", "FIRST"),
                        ],
                        default="ECONOMY",
                        help_text="flight class",
                        max_length=25,
                    ),
                ),
                (
                    "departure_date",
                    models.DateTimeField(
                        blank=True, help_text="Departure Date", null=True
                    ),
                ),
                (
                    "arrival_date",
                    models.DateTimeField(
                        blank=True, help_text="Arrival Date", null=True
                    ),
                ),
                (
                    "return_date",
                    models.DateTimeField(
                        blank=True, help_text="Return Date", null=True
                    ),
                ),
                (
                    "return_arrival_date",
                    models.DateTimeField(
                        blank=True, help_text="Return Date", null=True
                    ),
                ),
                (
                    "flying_from",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("flying_to", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "return_from",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("return_to", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "booking_reference",
                    models.CharField(
                        blank=True, help_text="Unique booking reference", max_length=20
                    ),
                ),
                (
                    "airiq_pnr",
                    models.CharField(blank=True, help_text="AirIQ PNR", max_length=20),
                ),
                (
                    "airline_pnr",
                    models.CharField(
                        blank=True, help_text="Airline PNR", max_length=20
                    ),
                ),
                (
                    "airiq_track_id",
                    models.CharField(
                        blank=True,
                        help_text="AirIQ tracking ID for API calls",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Booking Initiated"),
                            ("PENDING_PAYMENT", "Pending Payment"),
                            ("HELD", "Booking Held"),
                            ("CONFIRMED", "Confirmed"),
                            ("TICKETED", "Ticketed"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="INITIATED",
                        help_text="Flight booking status",
                        max_length=20,
                    ),
                ),
                (
                    "booking_mode",
                    models.CharField(
                        choices=[("REALTIME", "Real-time"), ("INVENTORY", "Inventory")],
                        default="REALTIME",
                        help_text="Booking mode",
                        max_length=10,
                    ),
                ),
                (
                    "selected_flight_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Selected flight option data",
                    ),
                ),
                (
                    "search_session_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Flight search session data"
                    ),
                ),
                (
                    "hold_expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Booking hold expiry time", null=True
                    ),
                ),
                (
                    "payment_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Payment lock expiry time (5 minutes)",
                        null=True,
                    ),
                ),
                (
                    "airiq_request_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Original AirIQ request data for booking",
                    ),
                ),
                (
                    "pricing_validation_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Pricing validation response data",
                    ),
                ),
                (
                    "fare_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Fare rules response from AirIQ for selected flights",
                    ),
                ),
                (
                    "airiq_response_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Latest AirIQ responses (booking/ticketing/etc.)",
                    ),
                ),
                (
                    "pricing_response_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw pricing response used to compute amounts",
                    ),
                ),
                (
                    "seatmap_response_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw seatmap response when seats are selected (optional)",
                    ),
                ),
                (
                    "airiq_pnrs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of AirIQ PNRs when supplier returns multiple",
                    ),
                ),
                (
                    "airline_pnrs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of Airline PNRs across all segments",
                    ),
                ),
                (
                    "airiq_track_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of AirIQ Track IDs if multiple bookings were created",
                    ),
                ),
                (
                    "booked_itineraries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Structured list of booked itineraries with segments and amounts",
                    ),
                ),
                (
                    "ticket_numbers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of ticket numbers for passengers",
                    ),
                ),
                (
                    "flight_ticket",
                    models.FileField(
                        blank=True, null=True, upload_to="booking/flight/"
                    ),
                ),
                (
                    "cancel_remark",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "reschedule_remark",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "FlightBookings",
            },
        ),
        migrations.CreateModel(
            name="HolidayPackageBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "no_days",
                    models.PositiveIntegerField(default=0, help_text="planned days"),
                ),
                ("available_start_date", models.DateTimeField(blank=True, null=True)),
                (
                    "enquired_holiday_package",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "confirmed_holiday_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="holiday_package.tourpackage",
                        verbose_name="holiday_package",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaxRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_type",
                    models.CharField(
                        choices=[
                            ("HOLIDAYPACK", "HOLIDAYPACK"),
                            ("HOTEL", "HOTEL"),
                            ("VEHICLE", "VEHICLE"),
                            ("FLIGHT", "FLIGHT"),
                        ],
                        default="HOTEL",
                        help_text="booking type.",
                        max_length=25,
                    ),
                ),
                (
                    "math_compare_symbol",
                    models.CharField(
                        choices=[
                            ("EQUALS", "EQUALS"),
                            ("LESS-THAN", "LESS-THAN"),
                            ("LESS-THAN-OR-EQUALS", "LESS-THAN-OR-EQUALS"),
                            ("GREATER-THAN", "GREATER-THAN"),
                            ("GREATER-THAN-OR-EQUALS", "GREATER-THAN-OR-EQUALS"),
                            ("BETWEEN", "BETWEEN"),
                        ],
                        default="EQUALS",
                        help_text="for comparison",
                        max_length=50,
                    ),
                ),
                (
                    "tax_rate_in_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="gst rate in percent",
                        max_digits=6,
                    ),
                ),
                ("amount1", models.PositiveIntegerField()),
                ("amount2", models.PositiveIntegerField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VehicleBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pickup_addr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dropoff_addr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pickup_time",
                    models.DateTimeField(
                        blank=True, help_text="Pickup date and time", null=True
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("CAR", "CAR"),
                            ("TRAVELLER", "TRAVELLER"),
                            ("BUS", "BUS"),
                        ],
                        default="CAR",
                        help_text="vehicle type.",
                        max_length=25,
                    ),
                ),
                (
                    "confirmed_vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="vehicle_management.vehicledetail",
                        verbose_name="confirmed_vehicle_booking",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "VehicleBookings",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_review",
                    models.JSONField(
                        default=apps.booking.models.default_property_review_json
                    ),
                ),
                (
                    "overall_rating",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Overall rating for the booked service.",
                        max_digits=3,
                    ),
                ),
                (
                    "agency_review",
                    models.JSONField(
                        default=apps.booking.models.default_agency_review_json,
                        null=True,
                    ),
                ),
                (
                    "overall_agency_rating",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Overall rating for the agency.",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the review was created.",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the review was last updated.",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Whether the review is active."
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_review",
                        to="booking.booking",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        help_text="Select the property for which this review is submitted.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_review",
                        to="hotels.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_review",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created",),
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.CharField(blank=True, default="", max_length=255)),
                ("header", models.CharField(blank=True, default="", max_length=255)),
                ("footer", models.CharField(blank=True, default="", max_length=255)),
                (
                    "invoice_number",
                    models.CharField(
                        db_index=True, default="", max_length=50, unique=True
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField(null=True)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "invoice_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="booking/invoices/"
                    ),
                ),
                ("billed_by_details", models.JSONField(default=dict, null=True)),
                ("billed_to_details", models.JSONField(default=dict, null=True)),
                ("supply_details", models.JSONField(default=dict, null=True)),
                ("items", models.JSONField(default=list, null=True)),
                ("payment_details", models.JSONField(default=list, null=True)),
                ("additional_options", models.JSONField(default=dict, null=True)),
                ("GST", models.PositiveIntegerField(default=0)),
                (
                    "GST_type",
                    models.CharField(blank=True, default="CGST/SGST", max_length=20),
                ),
                ("total", models.PositiveIntegerField(default=0)),
                ("total_amount", models.PositiveIntegerField(default=0)),
                ("total_tax", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PI", "PI"),
                            ("Pending", "Pending"),
                            ("Paid", "Paid"),
                            ("Overdue", "Overdue"),
                            ("Refunded", "Refunded"),
                            ("Cancelled", "Cancelled"),
                            ("Refund Pending", "Refund Pending"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("next_schedule_date", models.DateField(null=True)),
                ("tags", models.CharField(blank=True, max_length=255)),
                (
                    "reference",
                    models.CharField(
                        choices=[
                            ("Booking", "Booking"),
                            ("Subscription", "Subscription"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=20,
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=6, default=0, max_digits=15),
                ),
                (
                    "pro_member_discount",
                    models.DecimalField(decimal_places=6, default=0, max_digits=15),
                ),
                ("created_by", models.CharField(blank=True, default="", max_length=50)),
                ("updated_by", models.CharField(blank=True, default="", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices_billed_by",
                        to="org_managements.businessdetail",
                    ),
                ),
                (
                    "billed_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices_billed_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="HotelBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enquired_property",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "booking_slot",
                    models.CharField(
                        choices=[
                            ("4 Hrs", "4 Hrs"),
                            ("8 Hrs", "8 Hrs"),
                            ("12 Hrs", "12 Hrs"),
                            ("24 Hrs", "24 Hrs"),
                        ],
                        default="24 Hrs",
                        help_text="booking type.",
                        max_length=25,
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("DELUXE", "DELUXE"),
                            ("CLASSIC", "CLASSIC"),
                            ("PREMIUM", "PREMIUM"),
                        ],
                        default="DELUXE",
                        help_text="booked room type.",
                        max_length=25,
                    ),
                ),
                (
                    "checkin_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Check-in time for the property.",
                        null=True,
                    ),
                ),
                (
                    "checkout_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Check-out time for the property.",
                        null=True,
                    ),
                ),
                (
                    "bed_count",
                    models.PositiveIntegerField(default=1, help_text="bed count"),
                ),
                (
                    "requested_room_no",
                    models.PositiveIntegerField(
                        default=1, help_text="Requested room count"
                    ),
                ),
                (
                    "confirmed_room_details",
                    models.JSONField(
                        default=apps.booking.models.default_confirmed_room_json,
                        null=True,
                    ),
                ),
                (
                    "confirmed_checkin_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Confirmed Check-in time for the property.",
                        null=True,
                    ),
                ),
                (
                    "confirmed_checkout_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Confirmed Check-out time for the property.",
                        null=True,
                    ),
                ),
                (
                    "cancel_policy",
                    models.JSONField(
                        blank=True,
                        help_text="Sorted cancellation policies for the property",
                        null=True,
                    ),
                ),
                (
                    "cancellation_details",
                    models.JSONField(
                        blank=True,
                        help_text="Applied cancellation policy for this booking",
                        null=True,
                    ),
                ),
                (
                    "hotelier_receipt_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="hotels/booking_receipts/"
                    ),
                ),
                (
                    "confirmed_property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hotels.property",
                        verbose_name="booking_property",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hotels.room",
                        verbose_name="booking_room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HolidayPackageHotelDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "holiday_package_booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="booking.holidaypackagebooking",
                        verbose_name="holiday_package_booking",
                    ),
                ),
                (
                    "hotel_booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="booking.hotelbooking",
                        verbose_name="hotel_booking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlightPassenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "passenger_reference",
                    models.PositiveSmallIntegerField(
                        help_text="Passenger reference number (1, 2, 3...)"
                    ),
                ),
                (
                    "passenger_type",
                    models.CharField(
                        choices=[("ADT", "Adult"), ("CHD", "Child"), ("INF", "Infant")],
                        help_text="Passenger type",
                        max_length=3,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("MR", "Mr"),
                            ("MRS", "Mrs"),
                            ("MISS", "Miss"),
                            ("MS", "Ms"),
                            ("MSTR", "Master"),
                            ("DR", "Dr"),
                        ],
                        max_length=5,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                ("passport_number", models.CharField(blank=True, max_length=20)),
                ("passport_expiry", models.DateField(blank=True, null=True)),
                ("passport_issued_date", models.DateField(blank=True, null=True)),
                ("passport_country_code", models.CharField(blank=True, max_length=2)),
                (
                    "infant_with_passenger",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Passenger reference traveling with infant",
                        null=True,
                    ),
                ),
                ("frequent_flyer_number", models.CharField(blank=True, max_length=20)),
                ("frequent_flyer_airline", models.CharField(blank=True, max_length=3)),
                ("ticket_number", models.CharField(blank=True, max_length=20)),
                ("seat_number", models.CharField(blank=True, max_length=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flight_passengers",
                        to="booking.booking",
                    ),
                ),
                (
                    "flight_booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passengers",
                        to="booking.flightbooking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flight Passenger",
                "verbose_name_plural": "Flight Passengers",
                "db_table": "booking_flight_passenger",
                "ordering": ["passenger_reference"],
                "unique_together": {("flight_booking", "passenger_reference")},
            },
        ),
        migrations.CreateModel(
            name="FlightAncillaryService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("MEAL", "Meal"),
                            ("BAGGAGE", "Baggage"),
                            ("SEAT", "Seat"),
                            ("ASSURANCE", "Travel Assurance"),
                            ("PRIORITY_CHECK_IN", "Priority Check-in"),
                            ("BAGOUT", "Baggage First"),
                            ("OTHER", "Other Services"),
                        ],
                        max_length=20,
                    ),
                ),
                ("airiq_service_id", models.CharField(blank=True, max_length=100)),
                ("service_code", models.CharField(max_length=20)),
                ("service_description", models.CharField(max_length=200)),
                ("segment_reference", models.PositiveSmallIntegerField(default=1)),
                ("service_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flight_booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ancillary_services",
                        to="booking.flightbooking",
                    ),
                ),
                (
                    "passenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="booking.flightpassenger",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flight Ancillary Service",
                "verbose_name_plural": "Flight Ancillary Services",
                "db_table": "booking_flight_ancillary",
            },
        ),
        migrations.CreateModel(
            name="BookingPaymentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "merchant_transaction_id",
                    models.CharField(max_length=150, unique=True),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("code", models.CharField(blank=True, default="", max_length=50)),
                ("message", models.CharField(blank=True, default="", max_length=150)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("PAYMENT GATEWAY", "PAYMENT GATEWAY"),
                            ("WALLET", "WALLET"),
                            ("NBFC", "NBFC"),
                            ("DIRECT", "DIRECT"),
                            ("BANK TRANSFER", "BANK TRANSFER"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "payment_medium",
                    models.CharField(
                        choices=[
                            ("PHONE PAY", "PHONE PAY"),
                            ("PayU", "PayU"),
                            ("Idbook", "Idbook"),
                            ("Hotel", "Hotel"),
                            ("NEFT", "NEFT"),
                            ("RTGS", "RTGS"),
                            ("IMPS", "IMPS"),
                            ("UPI", "UPI"),
                            ("NET_BANKING", "Net Banking"),
                            ("Others", "Others"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=6, max_digits=20, null=True),
                ),
                ("is_transaction_success", models.BooleanField(default=False)),
                (
                    "transaction_for",
                    models.CharField(
                        choices=[
                            ("booking_confirmed", "booking_confirmed"),
                            ("booking_refund", "booking_refund"),
                            ("referral_booking", "referral_booking"),
                            ("booking_refund", "booking_refund"),
                            ("booking_cashback", "booking_cashback"),
                            ("signup_reward", "signup_reward"),
                            ("pro_member_bonus", "pro_member_bonus"),
                            ("pro_member_bonus_expiry", "pro_member_bonus_expiry"),
                            ("wallet_recharge", "wallet_recharge"),
                            ("others", "others"),
                        ],
                        default="others",
                        max_length=30,
                    ),
                ),
                ("transaction_details", models.JSONField(default=dict, null=True)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Card", "Card"),
                            ("Bank Transfer", "Bank Transfer"),
                            ("UPI", "UPI"),
                            ("Cheque", "Cheque"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        choices=[
                            ("Booking", "Booking"),
                            ("Subscription", "Subscription"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_payment",
                        to="booking.booking",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_history",
                        to="booking.invoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingMetaInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_created_date", models.DateTimeField(auto_now_add=True)),
                ("booking_confirmed_date", models.DateTimeField(blank=True, null=True)),
                ("booking_cancelled_date", models.DateTimeField(blank=True, null=True)),
                ("booking_completed_date", models.DateTimeField(blank=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meta_info",
                        to="booking.booking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commission", models.DecimalField(decimal_places=6, max_digits=20)),
                ("commission_type", models.CharField(max_length=20)),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                ("tax_amount", models.DecimalField(decimal_places=6, max_digits=20)),
                ("com_amnt", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "com_amnt_withtax",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                (
                    "tcs",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
                ),
                (
                    "tds",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
                ),
                (
                    "hotelier_amount",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
                ),
                (
                    "hotelier_amount_with_tax",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
                ),
                (
                    "final_payout",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.0,
                        help_text="for pay at hotel, the commision amount will be stored with                                       negative value, other case it is hotelier_amount_with_tax",
                        max_digits=20,
                    ),
                ),
                (
                    "is_payment_approved",
                    models.BooleanField(
                        default=True, help_text="Whether payment approved by admin"
                    ),
                ),
                (
                    "payout_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("ASSIGNED", "ASSIGNED"),
                            ("INITIATED", "INITIATED"),
                            ("INIT-FAIL", "INIT-FAIL"),
                            ("PAID", "PAID"),
                            ("FAILED", "FAILED"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_info",
                        to="booking.booking",
                    ),
                ),
                (
                    "latest_payout_reference",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_payout_reference",
                        to="hotels.propertypayoutdetails",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="flight_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="booking.flightbooking",
                verbose_name="flight_booking",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="holiday_package_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="booking.holidaypackagebooking",
                verbose_name="hotel_package_booking",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="hotel_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="booking.hotelbooking",
                verbose_name="hotel_booking",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="booking_user",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="vehicle_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="booking.vehiclebooking",
                verbose_name="vehicle_booking",
            ),
        ),
        migrations.CreateModel(
            name="AppliedCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_applied_coupon",
                        to="booking.booking",
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_applied",
                        to="coupons.coupon",
                    ),
                ),
            ],
        ),
    ]
