# Generated by Django 4.2.3 on 2024-10-11 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_flightbooking_holidaypackagebooking_vehiclebooking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaypackagebooking',
            name='available_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holidaypackagebooking',
            name='no_days',
            field=models.PositiveIntegerField(default=0, help_text='planned days'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='flight_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.flightbooking', verbose_name='flight_booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.vehiclebooking', verbose_name='vehicle_booking'),
        ),
    ]
