# Generated by Django 4.2.3 on 2025-11-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_add_guest_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='child_age_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='on_hold_end_time',
            field=models.DateTimeField(blank=True, help_text='Booking hold end time', null=True),
        ),
    ]
