# Generated by Django 4.2.3 on 2025-12-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_alter_booking_child_age_list_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightpassenger",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
