# Generated by Django 4.2.3 on 2025-12-18 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("org_resources", "0001_initial"),
        ("booking", "0004_alter_flightpassenger_date_of_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(help_text="Name of the event", max_length=200),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("conference", "Conference"),
                            ("wedding", "Wedding"),
                            ("corporate", "Corporate Event"),
                            ("seminar", "Seminar"),
                            ("exhibition", "Exhibition"),
                            ("festival", "Festival"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Type of event",
                        max_length=50,
                    ),
                ),
                (
                    "event_date",
                    models.DateTimeField(help_text="Event start date and time"),
                ),
                (
                    "event_end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Event end date and time (optional)",
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Event location (city/venue)", max_length=200
                    ),
                ),
                (
                    "attendee_count",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of attendees"
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("under_50000", "Under ₹50,000"),
                            ("50000_100000", "₹50,000 - ₹1,00,000"),
                            ("100000_250000", "₹1,00,000 - ₹2,50,000"),
                            ("250000_500000", "₹2,50,000 - ₹5,00,000"),
                            ("above_500000", "Above ₹5,00,000"),
                        ],
                        help_text="Budget range for the event",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "special_requirements",
                    models.TextField(
                        blank=True, default="", help_text="Any special requirements"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("documents_reviewed", "Documents Reviewed"),
                            ("quoted", "Quoted"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the booking",
                        max_length=50,
                    ),
                ),
                (
                    "itinerary_details",
                    models.JSONField(
                        default=dict,
                        help_text="Admin-added itinerary details",
                        null=True,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, default="", help_text="Admin notes and comments"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "EventBookings",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query_type",
                    models.CharField(
                        choices=[
                            ("HOLIDAYPACK", "HOLIDAYPACK"),
                            ("HOTEL", "HOTEL"),
                            ("VEHICLE", "VEHICLE"),
                            ("FLIGHT", "FLIGHT"),
                            ("VISA", "VISA"),
                            ("EVENT", "EVENT"),
                        ],
                        help_text="Type of query (HOTEL, FLIGHT, VISA, EVENT, etc.)",
                        max_length=25,
                    ),
                ),
                (
                    "query_reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique reference code for query",
                        max_length=500,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "booking_for",
                    models.CharField(
                        choices=[
                            ("B2C", "B2C Customer"),
                            ("CORPORATE", "Corporate"),
                            ("AGENT", "Agent"),
                        ],
                        default="B2C",
                        help_text="Booking made for whom",
                        max_length=50,
                    ),
                ),
                (
                    "referral_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EMPLOYEE", "Employee"),
                            ("USER", "User"),
                            ("AGENT", "Agent"),
                        ],
                        help_text="Type of referral",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "query_data",
                    models.JSONField(
                        default=dict,
                        help_text="Service-specific query data (destination, dates, etc.)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("documents_reviewed", "Documents Reviewed"),
                            ("quoted", "Quoted"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of query",
                        max_length=50,
                    ),
                ),
                (
                    "quote_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0.0,
                        help_text="Quoted amount",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "itinerary_details",
                    models.JSONField(
                        default=dict,
                        help_text="Admin-added itinerary details",
                        null=True,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, default="", help_text="Admin notes"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Query expiry date (for quotes)",
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Queries",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="VisaBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destination_country",
                    models.CharField(
                        help_text="Destination country for visa", max_length=100
                    ),
                ),
                ("travel_date", models.DateField(help_text="Intended travel date")),
                (
                    "visa_type",
                    models.CharField(
                        choices=[
                            ("tourist", "Tourist"),
                            ("business", "Business"),
                            ("transit", "Transit"),
                            ("student", "Student"),
                            ("work", "Work"),
                            ("other", "Other"),
                        ],
                        default="tourist",
                        help_text="Type of visa required",
                        max_length=50,
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Passport number",
                        max_length=50,
                    ),
                ),
                (
                    "passport_expiry",
                    models.DateField(
                        blank=True, help_text="Passport expiry date", null=True
                    ),
                ),
                (
                    "travel_purpose",
                    models.TextField(
                        blank=True, default="", help_text="Purpose of travel"
                    ),
                ),
                (
                    "documents_uploaded",
                    models.JSONField(
                        default=dict,
                        help_text="JSON field for document URLs",
                        null=True,
                    ),
                ),
                (
                    "special_requirements",
                    models.TextField(
                        blank=True, default="", help_text="Any special requirements"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("documents_reviewed", "Documents Reviewed"),
                            ("quoted", "Quoted"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the booking",
                        max_length=50,
                    ),
                ),
                (
                    "itinerary_details",
                    models.JSONField(
                        default=dict,
                        help_text="Admin-added itinerary details",
                        null=True,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, default="", help_text="Admin notes and comments"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "VisaBookings",
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="credit_note_pdf",
            field=models.FileField(
                blank=True,
                help_text="Credit note PDF (for refunds/adjustments)",
                null=True,
                upload_to="booking/invoices/credit_notes/",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("PROFORMA", "Proforma Invoice"),
                    ("INVOICE", "Final Invoice"),
                ],
                default="INVOICE",
                help_text="Invoice type - PROFORMA for queries, INVOICE for confirmed bookings",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="other_documents",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of other document URLs [{name, url, type, uploaded_at}]",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="proforma_pdf",
            field=models.FileField(
                blank=True,
                help_text="Proforma invoice PDF",
                null=True,
                upload_to="booking/invoices/proforma/",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="receipt_pdf",
            field=models.FileField(
                blank=True,
                help_text="Payment receipt PDF",
                null=True,
                upload_to="booking/invoices/receipts/",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="voucher_pdf",
            field=models.FileField(
                blank=True,
                help_text="Booking voucher PDF",
                null=True,
                upload_to="booking/invoices/vouchers/",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_type",
            field=models.CharField(
                choices=[
                    ("HOLIDAYPACK", "HOLIDAYPACK"),
                    ("HOTEL", "HOTEL"),
                    ("VEHICLE", "VEHICLE"),
                    ("FLIGHT", "FLIGHT"),
                    ("VISA", "VISA"),
                    ("EVENT", "EVENT"),
                ],
                default="HOTEL",
                help_text="booking type.",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_pdf",
            field=models.FileField(
                blank=True,
                help_text="Final invoice PDF",
                null=True,
                upload_to="booking/invoices/",
            ),
        ),
        migrations.AlterField(
            model_name="taxrule",
            name="booking_type",
            field=models.CharField(
                choices=[
                    ("HOLIDAYPACK", "HOLIDAYPACK"),
                    ("HOTEL", "HOTEL"),
                    ("VEHICLE", "VEHICLE"),
                    ("FLIGHT", "FLIGHT"),
                    ("VISA", "VISA"),
                    ("EVENT", "EVENT"),
                ],
                default="HOTEL",
                help_text="booking type.",
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="QueryCommunication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "communication_type",
                    models.CharField(
                        choices=[
                            ("NOTE", "Note"),
                            ("EMAIL", "Email"),
                            ("CALL", "Call"),
                            ("SMS", "SMS"),
                            ("STATUS_UPDATE", "Status Update"),
                            ("QUOTE_UPDATE", "Quote Update"),
                        ],
                        default="NOTE",
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=200)),
                ("message", models.TextField(help_text="Communication message/notes")),
                (
                    "attachments",
                    models.JSONField(
                        default=list, help_text="List of attachment URLs", null=True
                    ),
                ),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="Internal note (not visible to customer)",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "query",
                    models.ForeignKey(
                        help_text="Query this communication belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to="booking.query",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who added this communication",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "QueryCommunications",
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="query",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                help_text="Booking created from this query",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="from_query",
                to="booking.booking",
            ),
        ),
        migrations.AddField(
            model_name="query",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Company if query is for corporate",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="org_resources.companydetail",
            ),
        ),
        migrations.AddField(
            model_name="query",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                help_text="Proforma invoice for this query (converts to final invoice on booking)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="queries",
                to="booking.invoice",
            ),
        ),
        migrations.AddField(
            model_name="query",
            name="raised_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created/submitted the query",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="queries_raised",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="query",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Employee or user who referred this query",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="queries_referred",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="event_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="booking.eventbooking",
                verbose_name="event_booking",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="source_query",
            field=models.ForeignKey(
                blank=True,
                help_text="Query this booking was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="converted_bookings",
                to="booking.query",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="visa_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="booking.visabooking",
                verbose_name="visa_booking",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="source_query",
            field=models.ForeignKey(
                blank=True,
                help_text="Query this invoice was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="booking.query",
            ),
        ),
        migrations.AddIndex(
            model_name="query",
            index=models.Index(
                fields=["query_type", "status"], name="booking_que_query_t_d0d206_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="query",
            index=models.Index(
                fields=["company", "status"], name="booking_que_company_4a93fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="query",
            index=models.Index(
                fields=["raised_by", "status"], name="booking_que_raised__9d394d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="query",
            index=models.Index(
                fields=["booking_for", "status"], name="booking_que_booking_864981_idx"
            ),
        ),
    ]
