# Generated by Django 4.2.3 on 2024-10-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_flightbooking_departure_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_payment_made',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total Payment Made', max_digits=10),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='confirmed_checkin_time',
            field=models.DateTimeField(blank=True, help_text='Confirmed Check-in time for the property.', null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='confirmed_checkout_time',
            field=models.DateTimeField(blank=True, help_text='Confirmed Check-out time for the property.', null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='room_subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for stay in the room.', max_digits=10),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='service_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Service tax for the room.', max_digits=10),
        ),
    ]
