# Generated by Django 4.2.3 on 2026-01-13 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("org_resources", "0004_agentmarkupconfig"),
        ("booking", "0004_alter_flightpassenger_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent who created this booking (null if direct booking)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_bookings",
                to="org_resources.agentdetail",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="agent_markup_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Agent markup amount applied to this booking",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="agent_markup_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Agent markup percentage applied to this booking",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="booking_source",
            field=models.CharField(
                choices=[
                    ("AGENT", "Booked by Agent"),
                    ("DIRECT", "Booked by Customer Directly"),
                    ("AGENT_PORTAL", "Booked via Agent Portal"),
                ],
                default="DIRECT",
                help_text="Source of the booking",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="final_price_with_markup",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Final price including agent markup",
                max_digits=20,
                null=True,
            ),
        ),
    ]
