# Generated by Django 4.2.3 on 2024-10-24 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0001_initial'),
        ('booking', '0005_booking_confirmation_code_booking_total_payment_made_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclebooking',
            name='confirmed_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vehicle_management.vehicledetail', verbose_name='confirmed_vehicle_booking'),
        ),
    ]
