# Generated by Django 4.2.3 on 2026-01-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_booking_agent_booking_agent_markup_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_source",
            field=models.CharField(
                choices=[
                    ("AGENT", "Booked by Agent"),
                    ("CORPORATE", "Booked by Corporate User"),
                    ("B2C", "Booked by B2C User"),
                    ("GUEST", "Booked by Guest User"),
                ],
                default="DIRECT",
                help_text="Source of the booking",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bookingpaymentdetail",
            name="transaction_for",
            field=models.CharField(
                choices=[
                    ("booking_confirmed", "booking_confirmed"),
                    ("booking_refund", "booking_refund"),
                    ("referral_booking", "referral_booking"),
                    ("booking_cashback", "booking_cashback"),
                    ("signup_reward", "signup_reward"),
                    ("pro_member_bonus", "pro_member_bonus"),
                    ("pro_member_bonus_expiry", "pro_member_bonus_expiry"),
                    ("wallet_recharge", "wallet_recharge"),
                    ("others", "others"),
                ],
                default="others",
                max_length=30,
            ),
        ),
    ]
