# Generated by Django 4.2.3 on 2024-10-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_flightbooking_flight_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclebooking',
            name='service_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Service tax for the vehicle rental.', max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiclebooking',
            name='vehicle_subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Vehicle Rental Price.', max_digits=10),
        ),
    ]
