# Generated by Django 4.2.3 on 2026-02-24 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_eventbooking_query_visabooking_and_more"),
        ("booking", "0007_add_pay_with_commission"),
    ]

    operations = []
