# Generated by Django 4.2.3 on 2024-10-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_vehiclebooking_service_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaypackagebooking',
            name='holidaypack_subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Holiday Package Price', max_digits=10),
        ),
        migrations.AddField(
            model_name='holidaypackagebooking',
            name='service_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Service tax for the Holiday package.', max_digits=10),
        ),
    ]
