# Generated by Django 4.2.3 on 2024-10-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_holidaypackagebooking_holidaypack_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
