# Generated by Django 4.2.3 on 2024-10-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_booking_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='flight_subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Flight Ticket Price.', max_digits=10),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='service_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Service tax for flight ticket.', max_digits=10),
        ),
    ]
