# Generated by Django 4.2.3 on 2024-11-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_flightbooking_flight_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reference_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
