# Generated by Django 4.2.3 on 2024-11-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_booking_reference_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='deal_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='GST the booking', max_digits=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='gst_type',
            field=models.CharField(choices=[('IGST', 'IGST'), ('CGST/SGST', 'CGST/SGST')], default='', help_text='GST Type', max_length=25),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_tax',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Service tax for the booking', max_digits=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='subtotal',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Price for the booking', max_digits=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='discount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='final_amount',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Final amount after considering gst, discount', max_digits=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_payment_made',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Total Payment made', max_digits=15),
        ),
    ]
