# Generated by Django 4.2.3 on 2026-03-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0012_add_query_assigned_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="min_payment_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=None,
                help_text="Minimum rupee payment required for confirmation (optional).",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("payment_pending_verification", "Payment Pending Verification"),
                    ("confirmed", "Confirmed"),
                    ("canceled", "Canceled"),
                    ("completed", "Completed"),
                    ("no_show", "No Show"),
                    ("on_hold", "On Hold"),
                ],
                default="pending",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="eventbooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("assigned", "Assigned"),
                    ("documents_reviewed", "Documents Reviewed"),
                    ("quoted", "Quoted"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                help_text="Current status of the booking",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="query",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("assigned", "Assigned"),
                    ("documents_reviewed", "Documents Reviewed"),
                    ("quoted", "Quoted"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                help_text="Current status of query",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="visabooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("assigned", "Assigned"),
                    ("documents_reviewed", "Documents Reviewed"),
                    ("quoted", "Quoted"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                help_text="Current status of the booking",
                max_length=50,
            ),
        ),
    ]
