# Generated by Django 4.2.3 on 2024-11-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_remove_booking_deal_price_booking_gst_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='gst_amount',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='GST amount for the booking', max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='GST % for the booking', max_digits=15),
        ),
    ]
