# Generated by Cursor on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0013_alter_booking_min_payment_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="billed_to_type",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                help_text="Type of billed_to_ref_id (user/company/agent)",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="billed_to_ref_id",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                help_text="Reference id for billed_to_type (User.id / CompanyDetail.id / AgentDetail.id)",
            ),
        ),
    ]

