# Generated by Django 4.2.3 on 2024-11-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_booking_gst_amount_alter_booking_gst_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='gst_type',
            field=models.CharField(blank=True, choices=[('', ''), ('IGST', 'IGST'), ('CGST/SGST', 'CGST/SGST')], default='', help_text='GST Type', max_length=25),
        ),
    ]
