# Generated by Django 4.2.3 on 2026-05-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0014_invoice_billed_to_type_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingpaymentdetail",
            name="payment_medium",
            field=models.CharField(
                choices=[
                    ("PHONE PAY", "PHONE PAY"),
                    ("RAZORPAY", "RAZORPAY"),
                    ("PAYMENT GATEWAY", "PAYMENT GATEWAY"),
                    ("PayU", "PayU"),
                    ("Idbook", "Idbook"),
                    ("Hotel", "Hotel"),
                    ("NEFT", "NEFT"),
                    ("RTGS", "RTGS"),
                    ("IMPS", "IMPS"),
                    ("UPI", "UPI"),
                    ("NET_BANKING", "Net Banking"),
                    ("Others", "Others"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
