# Generated by Django 4.2.3 on 2024-11-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_booking_additional_notes_booking_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='additional_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
