# Generated by Django 4.2.3 on 2024-11-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_alter_booking_additional_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightbooking',
            name='flight_subtotal',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='service_tax',
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='arrival_date',
            field=models.DateTimeField(blank=True, help_text='Arrival Date', null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='flight_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='return_arrival_date',
            field=models.DateTimeField(blank=True, help_text='Return Date', null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='return_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='return_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
