# Generated by Django 4.2.3 on 2024-11-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_remove_flightbooking_flight_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidaypackagebooking',
            name='holidaypack_subtotal',
        ),
        migrations.RemoveField(
            model_name='holidaypackagebooking',
            name='service_tax',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='room_subtotal',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='service_tax',
        ),
        migrations.RemoveField(
            model_name='vehiclebooking',
            name='service_tax',
        ),
        migrations.RemoveField(
            model_name='vehiclebooking',
            name='vehicle_subtotal',
        ),
    ]
