# Generated by Django 4.2.3 on 2024-11-11 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0028_alter_usernotification_options'),
        ('booking', '0018_remove_holidaypackagebooking_holidaypack_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='org_resources.companydetail'),
        ),
    ]
