# Generated by Django 4.2.3 on 2024-11-28 05:56

import apps.booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_taxrule_created_taxrule_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='confirmed_room_details',
            field=models.JSONField(default=apps.booking.models.default_confirmed_room_json, null=True),
        ),
    ]
