# Generated by Django 4.2.3 on 2024-12-01 16:15

import apps.booking.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0037_delete_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0024_alter_hotelbooking_confirmed_room_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_review', models.JSONField(default=apps.booking.models.default_property_review_json)),
                ('overall_rating', models.DecimalField(decimal_places=2, help_text='Overall rating for the booked service.', max_digits=3)),
                ('agency_review', models.JSONField(default=apps.booking.models.default_agency_review_json)),
                ('overall_agency_rating', models.DecimalField(decimal_places=2, help_text='Overall rating for the agency.', max_digits=3)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time when the review was created.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date and time when the review was last updated.')),
                ('active', models.BooleanField(default=True, help_text='Whether the review is active.')),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_review', to='booking.booking')),
                ('property', models.ForeignKey(help_text='Select the property for which this review is submitted.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_review', to='hotels.property')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
