# Generated by Django 4.2.3 on 2024-12-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
