# Generated by Django 4.2.3 on 2024-12-13 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_booking_coupon_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=150)),
                ('payment_type', models.CharField(choices=[('PAYMENT GATEWAY', 'PAYMENT GATEWAY'), ('WALLET', 'WALLET'), ('NBFC', 'NBFC')], max_length=50)),
                ('payment_medium', models.CharField(choices=[('PHONE PAY', 'PHONE PAY'), ('Idbook', 'Idbook')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('is_transaction_success', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_payment', to='booking.booking')),
            ],
        ),
    ]
