# Generated by Django 4.2.3 on 2024-12-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_alter_bookingpaymentdetail_merchant_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpaymentdetail',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bookingpaymentdetail',
            name='message',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
