# Generated by Django 4.2.3 on 2024-12-21 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_bookingpaymentdetail_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='booking_slot',
        ),
    ]
