# Generated by Django 4.2.3 on 2024-12-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_remove_hotelbooking_booking_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='booking_slot',
            field=models.CharField(choices=[('4 Hrs', '4 Hrs'), ('8 Hrs', '8 Hrs'), ('12 Hrs', '12 Hrs'), ('24 Hrs', '24 Hrs')], default='24 Hrs', help_text='booking type.', max_length=25),
        ),
    ]
