# Generated by Django 4.2.3 on 2024-12-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_hotelbooking_booking_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='on_hold_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('completed', 'Completed'), ('no_show', 'No Show'), ('on_hold', 'On Hold')], default='pending', max_length=100),
        ),
    ]
