# Generated by Django 4.2.3 on 2024-12-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_booking_on_hold_end_time_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='child_age_count',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='requested_room_no',
            field=models.PositiveIntegerField(default=1, help_text='Requested room count'),
        ),
    ]
