# Generated by Django 4.2.3 on 2024-12-28 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_booking_child_age_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='child_age_count',
            new_name='child_age_list',
        ),
    ]
