# Generated by Django 4.2.3 on 2025-02-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0036_alter_appliedcoupon_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
