# Generated by Django 4.2.3 on 2025-03-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0037_booking_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='applicable_cancel_policy',
            field=models.JSONField(blank=True, help_text='Applied cancellation policy for this booking', null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='cancel_policy',
            field=models.JSONField(blank=True, help_text='Sorted cancellation policies for the property', null=True),
        ),
    ]
