# Generated by Django 4.2.3 on 2025-03-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0038_hotelbooking_applicable_cancel_policy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='applicable_cancel_policy',
            new_name='cancellation_details',
        ),
    ]
