# Generated by Django 4.2.3 on 2025-03-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0039_rename_applicable_cancel_policy_hotelbooking_cancellation_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpaymentdetail',
            name='transaction_for',
            field=models.CharField(choices=[('booking_confirmed', 'booking_confirmed'), ('booking_refund', 'booking_refund'), ('referral_booking', 'referral_booking'), ('booking_refund', 'booking_refund'), ('others', 'others')], default='others', max_length=30),
        ),
    ]
