# Generated by Django 4.2.3 on 2025-03-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0040_bookingpaymentdetail_transaction_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_checkin',
            field=models.BooleanField(default=False, help_text='Check_in status'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_checkout',
            field=models.BooleanField(default=False, help_text='Check_out status'),
        ),
    ]
