# Generated by Django 4.2.3 on 2025-03-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0041_booking_is_checkin_booking_is_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='overall_agency_rating',
            field=models.DecimalField(decimal_places=2, help_text='Overall rating for the agency.', max_digits=3, null=True),
        ),
    ]
