# Generated by Django 4.2.3 on 2025-03-24 13:09

import apps.booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0042_alter_review_overall_agency_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='agency_review',
            field=models.JSONField(default=apps.booking.models.default_agency_review_json, null=True),
        ),
    ]
