# Generated by Django 4.2.3 on 2025-03-26 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0043_alter_review_agency_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingMetaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_created_date', models.DateTimeField(auto_now_add=True)),
                ('booking_confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('booking_cancelled_date', models.DateTimeField(blank=True, null=True)),
                ('booking_completed_date', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_info', to='booking.booking')),
            ],
            options={
                'verbose_name': 'Booking Meta Info',
                'verbose_name_plural': 'Booking Meta Infos',
            },
        ),
    ]
