# Generated by Django 4.2.3 on 2025-04-02 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0044_bookingmetainfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.DecimalField(decimal_places=6, max_digits=20)),
                ('commission_type', models.CharField(max_length=20)),
                ('tax_percentage', models.DecimalField(decimal_places=6, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('com_amnt', models.DecimalField(decimal_places=6, max_digits=20)),
                ('com_amnt_withtax', models.DecimalField(decimal_places=6, max_digits=20)),
                ('tcs', models.DecimalField(decimal_places=6, default=0.0, max_digits=20)),
                ('tds', models.DecimalField(decimal_places=6, default=0.0, max_digits=20)),
                ('hotelier_amount', models.DecimalField(decimal_places=6, default=0.0, max_digits=20)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_info', to='booking.booking')),
            ],
        ),
    ]
