# Generated by Django 4.2.3 on 2025-04-04 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_managements', '0006_businessdetail_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0045_bookingcommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpaymentdetail',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='bookingpaymentdetail',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(blank=True, default='', max_length=255)),
                ('header', models.CharField(blank=True, default='', max_length=255)),
                ('footer', models.CharField(blank=True, default='', max_length=255)),
                ('invoice_number', models.CharField(db_index=True, default='', max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('billed_by_details', models.JSONField(default=dict, null=True)),
                ('billed_to_details', models.JSONField(default=dict, null=True)),
                ('supply_details', models.JSONField(default=dict, null=True)),
                ('items', models.JSONField(default=list, null=True)),
                ('GST', models.PositiveIntegerField(default=0)),
                ('GST_type', models.CharField(blank=True, default='CGST/SGST', max_length=20)),
                ('total', models.PositiveIntegerField(default=0)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('total_tax', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Pending', max_length=10)),
                ('next_schedule_date', models.DateField(null=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('created_by', models.CharField(blank=True, default='', max_length=50)),
                ('updated_by', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_billed_by', to='org_managements.businessdetail')),
                ('billed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_billed_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bookingpaymentdetail',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='booking.invoice'),
        ),
    ]
