# Generated by Django 4.2.3 on 2025-04-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0046_bookingpaymentdetail_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpaymentdetail',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Bank Transfer', 'Bank Transfer'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
