# Generated by Django 4.2.3 on 2025-04-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0047_alter_bookingpaymentdetail_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reference',
            field=models.CharField(choices=[('Booking', 'Booking'), ('Subscription', 'Subscription'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingpaymentdetail',
            name='reference',
            field=models.CharField(choices=[('Booking', 'Booking'), ('Subscription', 'Subscription'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
