# Generated by Django 4.2.3 on 2025-04-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0048_invoice_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpaymentdetail',
            name='payment_medium',
            field=models.CharField(choices=[('PHONE PAY', 'PHONE PAY'), ('Idbook', 'Idbook'), ('Hotel', 'Hotel')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpaymentdetail',
            name='payment_type',
            field=models.CharField(choices=[('PAYMENT GATEWAY', 'PAYMENT GATEWAY'), ('WALLET', 'WALLET'), ('NBFC', 'NBFC'), ('DIRECT', 'DIRECT')], max_length=50, null=True),
        ),
    ]
