# Generated by Django 4.2.3 on 2025-04-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0049_alter_bookingpaymentdetail_payment_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
    ]
