# Generated by Django 4.2.3 on 2025-04-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0050_invoice_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='booking/invoices/'),
        ),
    ]
