# Generated by Django 4.2.3 on 2025-04-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0051_invoice_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
