# Generated by Django 4.2.3 on 2025-04-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0052_invoice_pdf_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_url',
        ),
    ]
