# Generated by Django 4.2.3 on 2025-04-17 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0054_alter_bookingpaymentdetail_transaction_for'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-created_at',)},
        ),
    ]
