# Generated by Django 4.2.3 on 2025-04-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0055_alter_invoice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpaymentdetail',
            name='payment_medium',
            field=models.CharField(choices=[('PHONE PAY', 'PHONE PAY'), ('PayU', 'PayU'), ('Idbook', 'Idbook'), ('Hotel', 'Hotel')], max_length=50, null=True),
        ),
    ]
