# Generated by Django 4.2.3 on 2025-05-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0056_alter_bookingpaymentdetail_payment_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcommission',
            name='hotelier_amount_with_tax',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20),
        ),
    ]
