# Generated by Django 4.2.3 on 2025-05-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0057_bookingcommission_hotelier_amount_with_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpaymentdetail',
            name='transaction_for',
            field=models.CharField(choices=[('booking_confirmed', 'booking_confirmed'), ('booking_refund', 'booking_refund'), ('referral_booking', 'referral_booking'), ('booking_refund', 'booking_refund'), ('booking_cashback', 'booking_cashback'), ('signup_reward', 'signup_reward'), ('others', 'others')], default='others', max_length=30),
        ),
    ]
