# Generated by Django 4.2.3 on 2025-05-14 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0072_propertypayoutdetails'),
        ('booking', '0057_bookingcommission_hotelier_amount_with_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcommission',
            name='is_payment_approved',
            field=models.BooleanField(default=True, help_text='Whether payment approved by admin'),
        ),
        migrations.AddField(
            model_name='bookingcommission',
            name='latest_payout_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_payout_reference', to='hotels.propertypayoutdetails'),
        ),
        migrations.AddField(
            model_name='bookingcommission',
            name='payout_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('INITIATED', 'INITIATED'), ('INIT-FAIL', 'INIT-FAIL'), ('PAID', 'PAID'), ('FAILED', 'FAILED')], default='PENDING', max_length=50),
        ),
    ]
