# Generated by Django 4.2.3 on 2025-05-13 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0058_alter_bookingpaymentdetail_transaction_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='billed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices_billed_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
