# Generated by Django 4.2.3 on 2025-05-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0059_alter_invoice_billed_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pro_member_discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Discount percent for pro member'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pro_member_discount_value',
            field=models.PositiveSmallIntegerField(default=0, help_text='Discount value'),
        ),
    ]
