# Generated by Django 4.2.3 on 2025-05-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0060_booking_pro_member_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='hotelier_receipt_pdf',
            field=models.FileField(blank=True, null=True, upload_to='hotels/booking_receipts/'),
        ),
    ]
