# Generated by Django 4.2.3 on 2025-05-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0061_hotelbooking_hotelier_receipt_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pro_member_discount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
    ]
