# Generated by Django 4.2.3 on 2025-05-16 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0058_bookingcommission_is_payment_approved_and_more'),
        ('booking', '0062_invoice_pro_member_discount'),
    ]

    operations = [
    ]
