# Generated by Django 4.2.3 on 2025-05-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0063_merge_20250516_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingcommission',
            name='payout_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ASSIGNED', 'ASSIGNED'), ('INITIATED', 'INITIATED'), ('INIT-FAIL', 'INIT-FAIL'), ('PAID', 'PAID'), ('FAILED', 'FAILED')], default='PENDING', max_length=50),
        ),
    ]
