# Generated by Django 4.2.3 on 2025-05-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0064_alter_bookingcommission_payout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_direct_pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingcommission',
            name='final_payout',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='for pay at hotel, the commision amount will be stored with                                       negative value, other case it is hotelier_amount_with_tax', max_digits=20),
        ),
    ]
