# Generated by Django 4.2.3 on 2025-05-20 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0064_alter_bookingpaymentdetail_transaction_for'),
        ('booking', '0065_booking_is_direct_pay_bookingcommission_final_payout'),
    ]

    operations = [
    ]
