# Generated by Django 4.2.3 on 2025-05-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0066_merge_20250520_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_discount',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Total discount of a booking', max_digits=20),
        ),
    ]
