# Generated by Django 4.2.3 on 2025-05-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0067_booking_total_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_details',
            field=models.JSONField(default=list, null=True),
        ),
    ]
