# Generated by Django 4.2.3 on 2025-05-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0068_invoice_payment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='additional_options',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
