# Generated by Django 4.2.3 on 2025-05-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0070_alter_bookingpaymentdetail_transaction_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpaymentdetail',
            name='payment_medium',
            field=models.CharField(choices=[('PHONE PAY', 'PHONE PAY'), ('PayU', 'PayU'), ('Idbook', 'Idbook'), ('Hotel', 'Hotel'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('UPI', 'UPI'), ('NET_BANKING', 'Net Banking'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpaymentdetail',
            name='payment_type',
            field=models.CharField(choices=[('PAYMENT GATEWAY', 'PAYMENT GATEWAY'), ('WALLET', 'WALLET'), ('NBFC', 'NBFC'), ('DIRECT', 'DIRECT'), ('BANK TRANSFER', 'BANK_TRANSFER')], max_length=50, null=True),
        ),
    ]
