# Generated by Django 4.2.3 on 2025-05-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0071_alter_bookingpaymentdetail_payment_medium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpaymentdetail',
            name='payment_type',
            field=models.CharField(choices=[('PAYMENT GATEWAY', 'PAYMENT GATEWAY'), ('WALLET', 'WALLET'), ('NBFC', 'NBFC'), ('DIRECT', 'DIRECT'), ('BANK TRANSFER', 'BANK TRANSFER')], max_length=50, null=True),
        ),
    ]
