# Generated by Django 4.2.3 on 2025-10-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0072_alter_bookingpaymentdetail_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PI', 'PI'), ('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue'), ('Refunded', 'Refunded'), ('Cancelled', 'Cancelled'), ('Refund Pending', 'Refund Pending')], default='Pending', max_length=20),
        ),
    ]
