# Generated by Django 4.2.3 on 2025-11-11 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0073_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingmetainfo',
            options={},
        ),
        migrations.RemoveField(
            model_name='bookingmetainfo',
            name='booking_completed_date',
        ),
        migrations.RemoveField(
            model_name='bookingmetainfo',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='airiq_pnr',
            field=models.CharField(blank=True, help_text='AirIQ PNR', max_length=20),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='airiq_pnrs',
            field=models.JSONField(blank=True, default=list, help_text='List of AirIQ PNRs when supplier returns multiple'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='airiq_request_data',
            field=models.JSONField(blank=True, default=dict, help_text='Original AirIQ request data for booking'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='airiq_response_data',
            field=models.JSONField(blank=True, default=dict, help_text='Latest AirIQ responses (booking/ticketing/etc.)'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='airiq_track_id',
            field=models.CharField(blank=True, help_text='AirIQ tracking ID for API calls', max_length=255),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='airiq_track_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of AirIQ Track IDs if multiple bookings were created'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='airline_code',
            field=models.CharField(blank=True, help_text='Airline code (e.g., 6E, UK)', max_length=3),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='airline_pnr',
            field=models.CharField(blank=True, help_text='Airline PNR', max_length=20),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='airline_pnrs',
            field=models.JSONField(blank=True, default=list, help_text='List of Airline PNRs across all segments'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='booked_itineraries',
            field=models.JSONField(blank=True, default=list, help_text='Structured list of booked itineraries with segments and amounts'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='booking_mode',
            field=models.CharField(choices=[('REALTIME', 'Real-time'), ('INVENTORY', 'Inventory')], default='REALTIME', help_text='Booking mode', max_length=10),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='booking_reference',
            field=models.CharField(blank=True, help_text='Unique booking reference', max_length=20),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='cancel_remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='fare_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Fare rules response from AirIQ for selected flights'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, help_text='Booking hold expiry time', null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='payment_expires_at',
            field=models.DateTimeField(blank=True, help_text='Payment lock expiry time (5 minutes)', null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='pricing_response_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw pricing response used to compute amounts'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='pricing_validation_data',
            field=models.JSONField(blank=True, default=dict, help_text='Pricing validation response data'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='reschedule_remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='search_session_data',
            field=models.JSONField(blank=True, default=dict, help_text='Flight search session data'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='seatmap_response_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw seatmap response when seats are selected (optional)'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='selected_flight_data',
            field=models.JSONField(blank=True, default=dict, help_text='Selected flight option data'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Booking Initiated'), ('PENDING_PAYMENT', 'Pending Payment'), ('HELD', 'Booking Held'), ('CONFIRMED', 'Confirmed'), ('TICKETED', 'Ticketed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='INITIATED', help_text='Flight booking status', max_length=20),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='ticket_numbers',
            field=models.JSONField(blank=True, default=list, help_text='List of ticket numbers for passengers'),
        ),
        migrations.CreateModel(
            name='FlightPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_reference', models.PositiveSmallIntegerField(help_text='Passenger reference number (1, 2, 3...)')),
                ('passenger_type', models.CharField(choices=[('ADT', 'Adult'), ('CHD', 'Child'), ('INF', 'Infant')], help_text='Passenger type', max_length=3)),
                ('title', models.CharField(choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MISS', 'Miss'), ('MS', 'Ms'), ('MSTR', 'Master'), ('DR', 'Dr')], max_length=5)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('passport_number', models.CharField(blank=True, max_length=20)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('passport_issued_date', models.DateField(blank=True, null=True)),
                ('passport_country_code', models.CharField(blank=True, max_length=2)),
                ('infant_with_passenger', models.PositiveSmallIntegerField(blank=True, help_text='Passenger reference traveling with infant', null=True)),
                ('frequent_flyer_number', models.CharField(blank=True, max_length=20)),
                ('frequent_flyer_airline', models.CharField(blank=True, max_length=3)),
                ('ticket_number', models.CharField(blank=True, max_length=20)),
                ('seat_number', models.CharField(blank=True, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_passengers', to='booking.booking')),
                ('flight_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='booking.flightbooking')),
            ],
            options={
                'verbose_name': 'Flight Passenger',
                'verbose_name_plural': 'Flight Passengers',
                'db_table': 'booking_flight_passenger',
                'ordering': ['passenger_reference'],
                'unique_together': {('flight_booking', 'passenger_reference')},
            },
        ),
        migrations.CreateModel(
            name='FlightAncillaryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('MEAL', 'Meal'), ('BAGGAGE', 'Baggage'), ('SEAT', 'Seat'), ('ASSURANCE', 'Travel Assurance'), ('PRIORITY_CHECK_IN', 'Priority Check-in'), ('BAGOUT', 'Baggage First'), ('OTHER', 'Other Services')], max_length=20)),
                ('airiq_service_id', models.CharField(blank=True, max_length=100)),
                ('service_code', models.CharField(max_length=20)),
                ('service_description', models.CharField(max_length=200)),
                ('segment_reference', models.PositiveSmallIntegerField(default=1)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancillary_services', to='booking.flightbooking')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='booking.flightpassenger')),
            ],
            options={
                'verbose_name': 'Flight Ancillary Service',
                'verbose_name_plural': 'Flight Ancillary Services',
                'db_table': 'booking_flight_ancillary',
            },
        ),
    ]
