# Generated by Django 4.2.3 on 2025-11-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0074_alter_bookingmetainfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmetainfo',
            name='booking_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingmetainfo',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
