# Generated by Django 4.2.3 on 2025-10-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0074_alter_bookingmetainfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='airiq_request_data',
            field=models.JSONField(blank=True, default=dict, help_text='Original AirIQ request data for booking'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='payment_expires_at',
            field=models.DateTimeField(blank=True, help_text='Payment lock expiry time (5 minutes)', null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='pricing_validation_data',
            field=models.JSONField(blank=True, default=dict, help_text='Pricing validation response data'),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Booking Initiated'), ('PENDING_PAYMENT', 'Pending Payment'), ('HELD', 'Booking Held'), ('CONFIRMED', 'Confirmed'), ('TICKETED', 'Ticketed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='INITIATED', help_text='Flight booking status', max_length=20),
        ),
    ]
