# Generated by Django 4.2.3 on 2025-10-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0075_flightbooking_airiq_request_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='fare_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Fare rules response from AirIQ for selected flights'),
        ),
    ]
