# Generated by Django 4.2.3 on 2025-11-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0076_flightbooking_fare_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='airiq_response_data',
            field=models.JSONField(blank=True, default=dict, help_text='Latest AirIQ responses (booking/ticketing/etc.)'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='cancel_remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='reschedule_remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
