# Generated by Django 4.2.3 on 2025-11-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0077_flightbooking_airiq_response_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='pricing_response_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw pricing response used to compute amounts'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='seatmap_response_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw seatmap response when seats are selected (optional)'),
        ),
    ]
