# Generated by Django 4.2.3 on 2025-11-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0078_flightbooking_pricing_response_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='airiq_pnrs',
            field=models.JSONField(blank=True, default=list, help_text='List of AirIQ PNRs when supplier returns multiple'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='airiq_track_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of AirIQ Track IDs if multiple bookings were created'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='airline_pnrs',
            field=models.JSONField(blank=True, default=list, help_text='List of Airline PNRs across all segments'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='booked_itineraries',
            field=models.JSONField(blank=True, default=list, help_text='Structured list of booked itineraries with segments and amounts'),
        ),
    ]
