# Generated by Django 4.2.3 on 2025-11-07 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0079_flightbooking_airiq_pnrs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightancillaryservice',
            options={'verbose_name': 'Flight Ancillary Service', 'verbose_name_plural': 'Flight Ancillary Services'},
        ),
        migrations.RemoveField(
            model_name='flightancillaryservice',
            name='booking_completed_date',
        ),
        migrations.RemoveField(
            model_name='flightancillaryservice',
            name='date_updated',
        ),
        migrations.AlterModelTable(
            name='flightancillaryservice',
            table='booking_flight_ancillary',
        ),
    ]
