# Generated by Django 4.2.3 on 2025-11-13 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("booking", "0001_initial"),
        ("org_resources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelierPayoutLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.CharField(blank=True, max_length=100)),
                ("payout_status", models.PositiveSmallIntegerField(null=True)),
                ("payout_response", models.JSONField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SmsNotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile_number", models.CharField(max_length=20)),
                ("response", models.JSONField(blank=True, null=True)),
                (
                    "sms_for",
                    models.CharField(
                        choices=[
                            ("HOTEL_BOOKING_CANCEL", "Hotel Booking Cancellation"),
                            ("HOTEL_PAYMENT_REFUND", "Hotel Payment Refund"),
                            (
                                "WALLET_RECHARGE_CONFIRMATION",
                                "Wallet Recharge Confirmation",
                            ),
                            (
                                "WALLET_DEDUCTION_CONFIRMATION",
                                "Wallet Deduction Confirmation",
                            ),
                            (
                                "HOTEL_BOOKING_CONFIRMATION",
                                "Hotel Booking Confirmation",
                            ),
                            ("PAYMENT_FAILED_INFO", "Payment Failed Information"),
                            ("PAYMENT_PROCEED_INFO", "Payment Proceed Information"),
                            ("VERIFY", "Verify OTP"),
                            ("SIGNUP", "Signup OTP"),
                            ("LOGIN", "Login OTP"),
                            ("HOTEL_PROPERTY_ACTIVATION", "Property Activated"),
                            ("HOTEL_PROPERTY_DEACTIVATION", "Property Deactivated"),
                            (
                                "HOTELIER_BOOKING_NOTIFICATION",
                                "Hotelier Booking Notification",
                            ),
                            (
                                "HOTELER_BOOKING_CANCEL_NOTIFICATION",
                                "Hotelier Booking Cancel Notification",
                            ),
                            (
                                "HOTELER_PAYMENT_NOTIFICATION",
                                "Hotelier Payment Notification",
                            ),
                            (
                                "HOTELIER_PROPERTY_REVIEW_NOTIFICATION",
                                "Property Review Notification",
                            ),
                            ("HOTEL_PROPERTY_SUBMISSION", "Property Submission"),
                            ("other", "Other Notification"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SmsOtpLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile_number", models.CharField(blank=True, max_length=100)),
                ("response", models.JSONField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WalletTransactionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "merchant_transaction_id",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("x_verify", models.CharField(blank=True, default="", max_length=800)),
                ("request", models.JSONField(blank=True, null=True)),
                ("response", models.JSONField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wallet_company_transaction_logs",
                        to="org_resources.companydetail",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wallet_transaction_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSubscriptionLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pg_subid",
                    models.CharField(
                        blank=True,
                        help_text="payment gateway subscription id",
                        max_length=100,
                    ),
                ),
                (
                    "tnx_id",
                    models.CharField(
                        blank=True,
                        help_text="transaction id / request id",
                        max_length=100,
                    ),
                ),
                (
                    "api_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VPA-CHECK", "VPA-CHECK"),
                            ("CRT-SUB", "CRT-SUB"),
                            ("MANDATE", "MANDATE"),
                            ("MNDT-CLBAK", "MNDT-CLBAK"),
                            ("MNDT-STATCHK", "MNDT-STATCHK"),
                            ("RECUR-INIT", "RECUR-INIT"),
                            ("RECRINIT-CALBAK", "RECRINIT-CALBAK"),
                            ("RECUR-NOTIF", "RECUR-NOTIF"),
                            ("SUB-CANC", "SUB-CANC"),
                            ("SUBCANC-CALBAK", "SUBCANC-CALBAK"),
                            ("CMN-CALBAK", "CMN-CALBAK"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                ("status_code", models.IntegerField(null=True)),
                ("status_response", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="usersub_log",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_sub",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_subscription_log",
                        to="org_resources.usersubscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingRefundLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "merchant_refund_id",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "original_transaction_id",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("x_verify", models.CharField(blank=True, default="", max_length=800)),
                ("refund_amount", models.FloatField(default=0)),
                (
                    "status",
                    models.CharField(blank=True, default="initiated", max_length=50),
                ),
                (
                    "response_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "response_message",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("request", models.JSONField(blank=True, null=True)),
                ("response", models.JSONField(blank=True, null=True)),
                ("transaction_details", models.JSONField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="booking.booking",
                        verbose_name="booking_refund_logs",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingPaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "merchant_transaction_id",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("x_verify", models.CharField(blank=True, default="", max_length=800)),
                ("request", models.JSONField(blank=True, null=True)),
                ("response", models.JSONField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="booking.booking",
                        verbose_name="booking_payment_logs",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingInvoiceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_code", models.IntegerField(default=0)),
                ("response", models.JSONField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="booking.booking",
                        verbose_name="booking_invoice_logs",
                    ),
                ),
            ],
        ),
    ]
