# Generated by Django 4.2.3 on 2026-01-19 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("org_resources", "0004_agentmarkupconfig"),
        ("log_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransactionlog",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent associated with this wallet transaction",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="wallet_agent_transaction_logs",
                to="org_resources.agentdetail",
            ),
        ),
        migrations.AlterField(
            model_name="wallettransactionlog",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="wallet_company_transaction_logs",
                to="org_resources.companydetail",
            ),
        ),
        migrations.AlterField(
            model_name="wallettransactionlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="wallet_transaction_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
