# Generated by Django 4.2.3 on 2024-12-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_bookingpaymentdetail_code_and_more'),
        ('log_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_transaction_id', models.CharField(max_length=150)),
                ('request', models.JSONField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.booking', verbose_name='booking_payment_logs')),
            ],
        ),
    ]
