# Generated by Django 4.2.3 on 2024-12-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management', '0002_bookingpaymentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpaymentlog',
            name='x_verify',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='bookingpaymentlog',
            name='merchant_transaction_id',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
