# Generated by Django 4.2.3 on 2025-02-20 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_resources', '0029_subscriber_enquiry_email_enquiry_name_and_more'),
        ('log_management', '0003_bookingpaymentlog_x_verify_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_transaction_id', models.CharField(blank=True, default='', max_length=150)),
                ('x_verify', models.CharField(blank=True, default='', max_length=800)),
                ('request', models.JSONField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wallet_company_transaction_logs', to='org_resources.companydetail')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wallet_transaction_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
