# Generated by Django 4.2.3 on 2025-03-06 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0037_booking_is_reviewed'),
        ('log_management', '0005_smsotplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRefundLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_refund_id', models.CharField(blank=True, default='', max_length=150)),
                ('original_transaction_id', models.CharField(blank=True, default='', max_length=150)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=150)),
                ('x_verify', models.CharField(blank=True, default='', max_length=800)),
                ('refund_amount', models.FloatField(default=0)),
                ('status', models.CharField(blank=True, default='initiated', max_length=50)),
                ('response_code', models.CharField(blank=True, default='', max_length=100)),
                ('response_message', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('request', models.JSONField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('transaction_details', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.booking', verbose_name='booking_refund_logs')),
            ],
        ),
    ]
