# Generated by Django 4.2.3 on 2025-03-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management', '0006_bookingrefundlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20)),
                ('response', models.JSONField(blank=True, null=True)),
                ('sms_for', models.CharField(choices=[('HOTEL_BOOKING_CANCEL', 'Hotel Booking Cancellation'), ('HOTEL_PAYMENT_REFUND', 'Hotel Payment Refund'), ('WALLET_RECHARGE_CONFIRMATION', 'Wallet Recharge Confirmation'), ('WALLET_DEDUCTION_CONFIRMATION', 'Wallet Deduction Confirmation'), ('HOTEL_BOOKING_CONFIRMATION', 'Hotel Booking Confirmation'), ('PAYMENT_FAILED_INFO', 'Payment Failed Information'), ('PAYMENT_PROCEED_INFO', 'Payment Proceed Information'), ('VERIFY', 'Verify OTP'), ('SIGNUP', 'Signup OTP'), ('LOGIN', 'Login OTP'), ('other', 'Other Notification')], default='other', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
