# Generated by Django 4.2.3 on 2025-04-17 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_resources', '0037_remove_usersubscription_payment_frequency_and_more'),
        ('log_management', '0008_usersubscriptionlogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscriptionlogs',
            name='status_code',
        ),
        migrations.AddField(
            model_name='usersubscriptionlogs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usersub_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersubscriptionlogs',
            name='user_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_subscription_log', to='org_resources.usersubscription'),
        ),
    ]
