# Generated by Django 4.2.3 on 2025-05-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management', '0011_alter_smsnotificationlog_sms_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionlogs',
            name='tnx_id',
            field=models.CharField(blank=True, help_text='transaction id', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersubscriptionlogs',
            name='api_code',
            field=models.CharField(blank=True, choices=[('VPA-CHECK', 'VPA-CHECK'), ('CRT-SUB', 'CRT-SUB'), ('MANDATE', 'MANDATE'), ('MNDT-CLBAK', 'MNDT-CLBAK'), ('RECUR-INIT', 'RECUR-INIT'), ('RECRINIT-CALBAK', 'RECRINIT-CALBAK'), ('SUB-CANC', 'SUB-CANC'), ('SUBCANC-CALBAK', 'SUBCANC-CALBAK')], default='', max_length=50),
        ),
    ]
