# Generated by Django 4.2.3 on 2025-05-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management', '0013_alter_usersubscriptionlogs_api_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptionlogs',
            name='api_code',
            field=models.CharField(blank=True, choices=[('VPA-CHECK', 'VPA-CHECK'), ('CRT-SUB', 'CRT-SUB'), ('MANDATE', 'MANDATE'), ('MNDT-CLBAK', 'MNDT-CLBAK'), ('RECUR-INIT', 'RECUR-INIT'), ('RECRINIT-CALBAK', 'RECRINIT-CALBAK'), ('RECUR-NOTIF', 'RECUR-NOTIF'), ('SUB-CANC', 'SUB-CANC'), ('SUBCANC-CALBAK', 'SUBCANC-CALBAK'), ('CMN-CALBAK', 'CMN-CALBAK')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usersubscriptionlogs',
            name='tnx_id',
            field=models.CharField(blank=True, help_text='transaction id / request id', max_length=100),
        ),
    ]
