# Generated by Django 4.2.3 on 2025-05-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_management', '0014_alter_usersubscriptionlogs_api_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelierPayoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(blank=True, max_length=100)),
                ('payout_status', models.PositiveSmallIntegerField(null=True)),
                ('payout_response', models.JSONField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
