# Generated by Django 4.2.3 on 2025-10-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
    ]
