# Generated by Django 4.2.3 on 2025-10-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20251014_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirIQTokenCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(help_text='Cached authentication token')),
                ('expires_at', models.DateTimeField(help_text='Token expiration datetime')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'airiq_token_cache',
                'ordering': ['-created_at'],
            },
        ),
    ]
