# Generated by Django 4.2.3 on 2025-11-07 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0080_alter_flightancillaryservice_options_and_more'),
        ('flights', '0003_add_airiq_token_cache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightbooking',
            name='search_session',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='selected_flight',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='flightbookingpayment',
            name='booking',
        ),
        migrations.AlterUniqueTogether(
            name='passengerdetail',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='passengerdetail',
            name='booking',
        ),
        migrations.AlterUniqueTogether(
            name='seatselection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='seatselection',
            name='passenger',
        ),
        migrations.AlterField(
            model_name='airiqapilog',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to='booking.flightbooking'),
        ),
        migrations.DeleteModel(
            name='AncillaryService',
        ),
        migrations.DeleteModel(
            name='FlightBooking',
        ),
        migrations.DeleteModel(
            name='FlightBookingPayment',
        ),
        migrations.DeleteModel(
            name='PassengerDetail',
        ),
        migrations.DeleteModel(
            name='SeatSelection',
        ),
    ]
