# Generated by Django 4.2.3 on 2023-07-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='amenitycategory',
            name='user',
        ),
    ]
