# Generated by Django 4.2.3 on 2025-12-22 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("org_resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydetail",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companydetail",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
