# Generated by Django 4.2.3 on 2025-12-27 04:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("org_resources", "0002_companydetail_created_companydetail_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_name", models.CharField(max_length=50)),
                (
                    "agent_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "agent_logo",
                    models.FileField(blank=True, null=True, upload_to="agent/logo/"),
                ),
                (
                    "agent_phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "agent_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address of the agent.",
                        max_length=254,
                        null=True,
                        validators=[django.core.validators.EmailValidator],
                    ),
                ),
                ("agent_website", models.URLField(blank=True, null=True)),
                ("gstin_no", models.CharField(blank=True, max_length=100, null=True)),
                ("pan_no", models.CharField(blank=True, max_length=100, null=True)),
                ("registered_address", models.TextField(blank=True, null=True)),
                (
                    "contact_person_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("designation", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "contact_email_address",
                    models.EmailField(
                        blank=True,
                        help_text="Email address of the contact person.",
                        max_length=254,
                        null=True,
                        validators=[django.core.validators.EmailValidator],
                    ),
                ),
                ("district", models.CharField(blank=True, max_length=20, null=True)),
                ("state", models.CharField(default="", max_length=30)),
                ("country", models.CharField(default="INDIA", max_length=25)),
                ("pin_code", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Google map URL",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("latitude", models.FloatField(default=0, help_text="Latitude")),
                ("longitude", models.FloatField(default=0, help_text="Longitude")),
                ("approved", models.BooleanField(default=False)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the agent is active."
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "added_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_list",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Agent Details",
            },
        ),
    ]
