# Generated by Django 4.2.3 on 2026-01-13 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("org_resources", "0003_agentdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentMarkupConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_markup_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Default markup percentage (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "default_markup_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0.0,
                        help_text="Default fixed markup amount (if markup_type is FIXED)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "markup_type",
                    models.CharField(
                        choices=[("PERCENT", "Percentage"), ("FIXED", "Fixed Amount")],
                        default="PERCENT",
                        help_text="Type of markup: percentage or fixed amount",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this markup configuration is active",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.OneToOneField(
                        help_text="Agent this markup configuration belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markup_config",
                        to="org_resources.agentdetail",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Agent Markup Configurations",
            },
        ),
    ]
