# Generated by Django 4.2.3 on 2026-04-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org_resources", "0005_messagetemplate_metadata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messagetemplate",
            options={"ordering": ["template_code"]},
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Internal display name (optional).",
                max_length=255,
            ),
        ),
    ]
