# Generated by Django 4.2.3 on 2026-05-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org_resources", "0007_alter_messagetemplate_template_type_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="payment_medium",
            field=models.CharField(
                choices=[
                    ("PHONE PAY", "PHONE PAY"),
                    ("RAZORPAY", "RAZORPAY"),
                    ("PAYMENT GATEWAY", "PAYMENT GATEWAY"),
                    ("PayU", "PayU"),
                    ("Idbook", "Idbook"),
                    ("Hotel", "Hotel"),
                    ("NEFT", "NEFT"),
                    ("RTGS", "RTGS"),
                    ("IMPS", "IMPS"),
                    ("UPI", "UPI"),
                    ("NET_BANKING", "Net Banking"),
                    ("Others", "Others"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
