# Generated by Django 4.2.3 on 2024-01-27 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_resources', '0008_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=200)),
                ('file_id', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('tags', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('size', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=20)),
                ('version_name', models.CharField(max_length=200)),
                ('version_id', models.CharField(max_length=200)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
