# Generated by Django 4.2.3 on 2024-09-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0010_alter_uploadedmedia_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='gstin_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='pan_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
