# Generated by Django 4.2.3 on 2024-10-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0011_companydetail_gstin_no_companydetail_pan_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='domain_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
