# Generated by Django 4.2.3 on 2024-10-04 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_resources', '0012_companydetail_domain_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetail',
            name='user',
        ),
        migrations.AddField(
            model_name='companydetail',
            name='added_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
