# Generated by Django 4.2.3 on 2024-10-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0013_remove_companydetail_user_companydetail_added_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
