# Generated by Django 4.2.3 on 2024-10-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0014_companydetail_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetail',
            name='full_address',
        ),
        migrations.AddField(
            model_name='companydetail',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='contact_email_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='registered_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='company_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='company_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='district',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='location',
            field=models.CharField(blank=True, help_text='Google map URL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='pin_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
