# Generated by Django 4.2.3 on 2024-10-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0015_remove_companydetail_full_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to='company/logo/'),
        ),
    ]
