# Generated by Django 4.2.3 on 2024-10-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0016_alter_companydetail_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='registered_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
