# Generated by Django 4.2.3 on 2024-10-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0017_alter_companydetail_registered_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the company is active.'),
        ),
    ]
