# Generated by Django 4.2.3 on 2024-10-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0018_companydetail_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, max_length=150, null=True)),
                ('country_short_name', models.CharField(blank=True, max_length=20, null=True)),
                ('country_phone_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country_details', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
