# Generated by Django 4.2.3 on 2024-10-23 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0020_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='company_email',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='company_phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='contact_email_address',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
