# Generated by Django 4.2.3 on 2024-10-23 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0021_alter_companydetail_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='contact_email_address',
            field=models.CharField(max_length=50, validators=[django.core.validators.EmailValidator]),
        ),
    ]
