# Generated by Django 4.2.3 on 2024-10-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0024_companydetail_business_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='state',
            field=models.CharField(default='', max_length=30),
        ),
    ]
