# Generated by Django 4.2.3 on 2025-03-18 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0030_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscriprion_type',
            new_name='subscription_type',
        ),
    ]
