# Generated by Django 4.2.3 on 2025-03-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0030_messagetemplate'),
        ('org_resources', '0031_rename_subscriprion_type_subscription_subscription_type'),
    ]

    operations = [
    ]
