# Generated by Django 4.2.3 on 2025-03-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0032_merge_20250319_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagetemplate',
            old_name='temp_id',
            new_name='message_id',
        ),
        migrations.RenameField(
            model_name='messagetemplate',
            old_name='temp_description',
            new_name='template_code',
        ),
        migrations.RenameField(
            model_name='messagetemplate',
            old_name='temp_message',
            new_name='template_message',
        ),
    ]
