# Generated by Django 4.2.3 on 2025-04-16 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org_resources', '0033_rename_temp_id_messagetemplate_message_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_subid', models.CharField(blank=True, help_text='payment gateway subscription id', max_length=100)),
                ('merchant_userid', models.CharField(blank=True, max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('notification_id', models.CharField(blank=True, max_length=100)),
                ('payment_frequency', models.CharField(choices=[('MONTHLY', 'MONTHLY'), ('YEARLY', 'YEARLY'), ('ONCE', 'ONCE')], default='', max_length=50)),
                ('payment_type', models.CharField(choices=[('PAYMENT GATEWAY', 'PAYMENT GATEWAY'), ('WALLET', 'WALLET'), ('NBFC', 'NBFC'), ('DIRECT', 'DIRECT')], default='', max_length=50)),
                ('payment_medium', models.CharField(choices=[('PHONE PAY', 'PHONE PAY'), ('Idbook', 'Idbook'), ('Hotel', 'Hotel')], default='', max_length=50)),
                ('upi_id', models.CharField(blank=True, default='', max_length=50)),
                ('is_upi_valid', models.BooleanField(default=False)),
                ('sub_start_date', models.DateTimeField(null=True)),
                ('sub_end_date', models.DateTimeField(null=True)),
                ('last_paid_date', models.DateTimeField(null=True)),
                ('next_payment_date', models.DateTimeField(null=True)),
                ('subscription_amount', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0, help_text='considers advance amount if opted')),
                ('paid', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('idb_sub', models.ForeignKey(help_text='Idbook subscription', on_delete=django.db.models.deletion.CASCADE, related_name='user_idbsub', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
