# Generated by Django 4.2.3 on 2025-04-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0033_rename_temp_id_messagetemplate_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
