# Generated by Django 4.2.3 on 2025-04-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0033_rename_temp_id_messagetemplate_message_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicAdminConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
