# Generated by Django 4.2.3 on 2025-04-18 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0034_basicadminconfig'),
        ('org_resources', '0034_usernotification_group_name'),
    ]

    operations = [
    ]
