# Generated by Django 4.2.3 on 2025-04-16 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0035_remove_usersubscription_idb_sub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='idb_sub',
            field=models.ForeignKey(help_text='Idbook subscription', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_idbsub', to='org_resources.subscription'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='mandate_tnx_id',
            field=models.CharField(blank=True, help_text='Mandate transaction id', max_length=100),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='merchant_subid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
