# Generated by Django 4.2.3 on 2025-04-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0036_usersubscription_idb_sub_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='payment_frequency',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='sub_workflow',
            field=models.CharField(choices=[('PENNY_DROP', 'PENNY_DROP'), ('TRANSACTION', 'TRANSACTION')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='transaction_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
