# Generated by Django 4.2.3 on 2025-04-21 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0035_merge_20250418_1058'),
        ('org_resources', '0038_rename_transaction_id_usersubscription_recrinit_tnx_id_and_more'),
    ]

    operations = [
    ]
