# Generated by Django 4.2.3 on 2025-04-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0039_merge_20250421_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='payment_medium',
            field=models.CharField(choices=[('PHONE PAY', 'PHONE PAY'), ('PayU', 'PayU'), ('Idbook', 'Idbook'), ('Hotel', 'Hotel')], default='', max_length=50),
        ),
    ]
