# Generated by Django 4.2.3 on 2025-05-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0040_alter_usersubscription_payment_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='is_cancel_initiated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
