# Generated by Django 4.2.3 on 2025-05-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0042_usersubscription_cancel_tnx_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subrecurringtransaction',
            name='invoice_display_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subrecurringtransaction',
            name='notify_request_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='transaction_amount',
            field=models.IntegerField(default=0, help_text='last transaction amount'),
        ),
    ]
