# Generated by Django 4.2.3 on 2025-05-08 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0042_usersubscription_cancel_tnx_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('feature_key', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('level', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='org_resources.subscription')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
