# Generated by Django 4.2.3 on 2025-05-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0043_featuresubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuresubscription',
            options={'ordering': ['level']},
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, help_text='Discount for Subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_type',
            field=models.CharField(choices=[('AMOUNT', 'AMOUNT'), ('PERCENT', 'PERCENT')], default='PERCENT', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='final_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
