# Generated by Django 4.2.3 on 2025-05-09 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0043_subrecurringtransaction_invoice_display_no_and_more'),
        ('org_resources', '0045_subscription_is_popular'),
    ]

    operations = [
    ]
