# Generated by Django 4.2.3 on 2025-05-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0046_merge_20250509_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='last_mandate_check',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='mandate_status',
            field=models.CharField(choices=[('pending', 'pending'), ('initiated', 'initiated'), ('active', 'active'), ('failed', 'failed'), ('cancel_initiated', 'cancel_initiated'), ('cancelled', 'cancelled'), ('cancel_failed', 'cancel_failed'), ('expired', 'expired')], default='pending', max_length=50),
        ),
    ]
