# Generated by Django 4.2.3 on 2025-05-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0047_usersubscription_last_mandate_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('GENERAL', 'GENERAL'), ('OFFERS', 'OFFERS'), ('BOOKING', 'BOOKING'), ('MEMBERSHIP', 'MEMBERSHIP')], default='GENERAL', max_length=50),
        ),
    ]
