# Generated by Django 4.2.3 on 2025-06-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_resources', '0050_alter_usersubscription_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicRulesConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_limit', models.PositiveIntegerField(default=0, help_text='Start range of bookings or other things')),
                ('end_limit', models.PositiveIntegerField(default=0, help_text='End range of bookings or other things')),
                ('value', models.PositiveIntegerField(default=0, help_text='Percent or value of the respective discount, cashback etc.')),
                ('rules_for', models.CharField(choices=[('PRO_DISCOUNT', 'PRO_DISCOUNT'), ('PRO_CASHBACK', 'PRO_CASHBACK'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
